language: python
python:
          - "3.5"
before_install:
          - mv travis_secrets.yaml secrets.yaml
install:
          - pip3 install homeassistant
         #- pyenv local 3.5
script:
          - hass -c . --script check_config
