- id: house_tod_schoolday_morning
  alias: "House ToD Schoolday Morning"
  trigger:
    platform: time
    at: "06:00"
  condition:
    condition: state
    entity_id: "binary_sensor.workday_sensor"
    state: "on"
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.house_time_of_day
      option: "Morning"

- id: house_tod_weekend_morning
  alias: "House ToD Weekend Morning"
  trigger:
    platform: time
    at: "07:30"
  condition:
    condition: state
    entity_id: "binary_sensor.workday_sensor"
    state: "off"
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.house_time_of_day
      option: "Morning"

- id: house_tod_schoolday_day
  alias: "House ToD Schoolday Day"
  trigger:
    platform: time
    at: "07:30"
  condition:
    condition: state
    entity_id: "binary_sensor.workday_sensor"
    state: "on"
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.house_time_of_day
      option: "Day"

- id: house_tod_weekend_day
  alias: "House ToD Weekend Day"
  trigger:
    platform: time
    at: "07:30"
  condition:
    condition: state
    entity_id: "binary_sensor.workday_sensor"
    state: "off"
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.house_time_of_day
      option: "Day"

- id: house_tod_weekend_naptime
  alias: "House ToD Weekend Nap Time"
  trigger:
    platform: time
    at: "13:00"
  condition:
    condition: state
    entity_id: "binary_sensor.workday_sensor"
    state: "off"
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.house_time_of_day
      option: "Naptime"

- id: house_tod_schoolday_afternoon
  alias: "House ToD Schoolday Afternoon"
  trigger:
    platform: time
    at: "15:00"
  condition:
    condition: state
    entity_id: "binary_sensor.workday_sensor"
    state: "on"
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.house_time_of_day
      option: "Afternoon"

- id: house_tod_weekend_afternoon
  alias: "House ToD Weekend Afternoon"
  trigger:
    platform: time
    at: "15:00"
  condition:
    condition: state
    entity_id: "binary_sensor.workday_sensor"
    state: "off"
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.house_time_of_day
      option: "Afternoon"

- id: house_tod_schoolday_evening
  alias: "House ToD Schoolday Evening"
  trigger:
    platform: sun
    event: sunset
    offset: "00:00:00"
  condition:
    condition: state
    entity_id: "binary_sensor.workday_sensor"
    state: "on"
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.house_time_of_day
      option: "Evening"

- id: house_tod_weekend_evening
  alias: "House ToD Weekend Evening"
  trigger:
    platform: sun
    event: sunset
    offset: "00:00:00"
  condition:
    condition: state
    entity_id: "binary_sensor.workday_sensor"
    state: "off"
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.house_time_of_day
      option: "Evening"

- id: house_tod_schoolday_night
  alias: "House ToD Schoolday Night"
  trigger:
    platform: time
    at: "21:00"
  condition:
    condition: state
    entity_id: "binary_sensor.workday_sensor"
    state: "on"
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.house_time_of_day
      option: "Night"

- id: house_tod_weekend_night
  alias: "House ToD Weekend Night"
  trigger:
    platform: time
    at: "21:30"
  condition:
    condition: state
    entity_id: "binary_sensor.workday_sensor"
    state: "off"
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.house_time_of_day
      option: "Night"
