- id: backyard_lights_on_when_back_door_open
  alias: Evening Back Yard Lights When Door Opened
  trigger:
    platform: state
    entity_id: binary_sensor.back_door
    to: 'true'
  condition:
    condition: sun
    after: sunset
    after_offset: -01:00:00
  action:
    service: homeassistant.turn_on
    entity_id: scene.backyard_lights_evening_on
- id: backyard_lights_vacancy_off
  alias: Back Yard Lights Off When Movement Stopped
  trigger:
    platform: state
    entity_id: binary_sensor.deck_motion
    to: 'off'
    for:
      minutes: 5
  action:
    service: scene.turn_on
    entity_id: scene.backyard_lights_off
- id: heidi_heater_thermostat_off
  alias: Heidi Heater Thermostat Off
  trigger:
    platform: numeric_state
    entity_id: sensor.heidi_multisensor_temperature
    above: 72.0
    for:
      minutes: 5
  action:
    service: homeassistant.turn_off
    entity_id: switch.heidi_heater
- id: heidi_heater_thermostat_on
  alias: Heidi Heater Thermostat On
  trigger:
    platform: numeric_state
    entity_id: sensor.heidi_multisensor_temperature
    below: 70.0
    for:
      minutes: 5
  action:
    service: homeassistant.turn_on
    entity_id: switch.heidi_heater
- id: mirror_bedtime_input_boolean_on
  alias: Mirror House Bedtime On to Input Boolean
  trigger:
    platform: state
    entity_id: binary_sensor.bedtime
    to: 'on'
  condition:
    condition: state
    entity_id: binary_sensor.bedtime
    state: 'on'
  action:
    service: input_boolean.turn_on
    data:
      entity_id: input_boolean.bedtime
- id: mirror_bedtime_input_boolean_off
  alias: Mirror House Bedtime Off to Input Boolean
  trigger:
    platform: state
    entity_id: binary_sensor.bedtime
    to: 'off'
  condition:
    condition: state
    entity_id: binary_sensor.bedtime
    state: 'off'
  action:
    service: input_boolean.turn_off
    data:
      entity_id: input_boolean.bedtime
- id: noah_lights_off_at_bedtime
  alias: Turn Noah Lights Off at Bedtime
  trigger:
  - platform: time
    at: '20:00:00'
  condition:
    condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
    service: light.turn_off
    entity_id: light.noah
- id: '1578857725197'
  alias: House Bed Time Lights and Security
  description: ''
  trigger:
  - at: '20:30'
    platform: time
  condition: []
  action:
  - scene: scene.house_bed_time
- id: '1579134844492'
  alias: Restart Home Assistant
  description: Restart Home Assistant Every Day
  trigger:
  - at: '3:00:00'
    platform: time
  condition: []
  action:
  - service: homeassistant.restart
- id: living_room_off_on_restart
  alias: Living Room Off on HA Restart
  trigger:
    platform: homeassistant
    event: start
  action:
  - service: switch.turn_off
    entity_id: switch.family_fan_lights
- id: '1592000426606'
  alias: Open Susan Garage when Susan Arrives Home
  description: ''
  trigger:
  - entity_id: binary_sensor.susan_at_home
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - after: '7:00'
    before: '21:00'
    condition: time
  action:
  - data: {}
    entity_id: cover.susan_garage
    service: cover.open_cover
