- id: backyard_lights_on_when_back_door_open
  alias: Evening Back Yard Lights When Door Opened
  trigger:
    platform: state
    entity_id: binary_sensor.back_door
    to: 'true'
  condition:
    condition: sun
    after: sunset
    after_offset: -01:00:00
  action:
    service: homeassistant.turn_on
    entity_id: scene.backyard_lights_evening_on
- id: heidi_heater_thermostat_off
  alias: Heidi Heater Thermostat Off
  trigger:
  - platform: numeric_state
    entity_id: sensor.heidi_temperature
    above: '75'
    for:
      hours: 0
      minutes: 10
      seconds: 0
      milliseconds: 0
  action:
  - service: homeassistant.turn_off
    entity_id: switch.heidi_heater
  mode: single
- id: heidi_heater_thermostat_on
  alias: Heidi Heater Thermostat On
  trigger:
  - platform: numeric_state
    entity_id: sensor.heidi_temperature
    below: '71'
    for:
      minutes: 5
  action:
  - service: homeassistant.turn_on
    entity_id: switch.heidi_heater
  mode: single
- id: mirror_bedtime_input_boolean_on
  alias: Mirror House Bedtime On to Input Boolean
  trigger:
    platform: state
    entity_id: binary_sensor.bedtime
    to: 'on'
  condition:
    condition: state
    entity_id: binary_sensor.bedtime
    state: 'on'
  action:
    service: input_boolean.turn_on
    data:
      entity_id: input_boolean.bedtime
- id: mirror_bedtime_input_boolean_off
  alias: Mirror House Bedtime Off to Input Boolean
  trigger:
    platform: state
    entity_id: binary_sensor.bedtime
    to: 'off'
  condition:
    condition: state
    entity_id: binary_sensor.bedtime
    state: 'off'
  action:
    service: input_boolean.turn_off
    data:
      entity_id: input_boolean.bedtime
- id: noah_lights_off_at_bedtime
  alias: Turn Noah Lights Off at Bedtime
  trigger:
  - platform: time
    at: '20:00:00'
  condition:
    condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
    service: light.turn_off
    entity_id: light.noah_lights
- id: '1578857725197'
  alias: House Bed Time Lights and Security
  description: ''
  trigger:
  - at: '20:29:00'
    platform: time
  condition: []
  action:
  - scene: scene.evening_security_check
  mode: single
- id: '1579134844492'
  alias: Restart Home Assistant
  description: Restart Home Assistant Every Day
  trigger:
  - at: '8:30:00'
    platform: time
  condition: []
  action:
  - service: homeassistant.restart
  mode: single
- id: '1598537302'
  alias: Turn Off Office Heater after 1 Hour
  description: ''
  trigger:
    platform: state
    entity_id: switch.office_heater
    to: to
    for: 01:00:00
  action:
    service: switch.turn_off
    entity_id: switch.office_heater
- id: '1610412320301'
  alias: Lights On with Night Pantry Access
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.pantry_door
    from: 'off'
    to: 'on'
  condition:
  - condition: time
    after: '22:30'
    before: '6:15'
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
  action:
  - service: scene.turn_on
    data: {}
    entity_id: scene.alert_lights
  mode: single
- id: '1612915867487'
  alias: Entry Scene Switch
  description: Entry Lights Scene Activated Switch
  use_blueprint:
    path: scene_switch.yaml
    input:
      switch_entity: switch.entry_lights
      on_scene: scene.entry_dining_on
      off_scene: scene.entry_dining_off
- id: '1612916883325'
  alias: Kids Study Scene Switch
  description: Change scene based on the state of the Kid's Study overhead lights.
  use_blueprint:
    path: scene_switch.yaml
    input:
      switch_entity: switch.kids_study_lights
      on_scene: scene.kids_study_on
      off_scene: scene.kids_study_off
- id: '1612917007753'
  alias: Craft Scene Switch
  description: Turn on or off all Craft Room lights based on the state of the Overhead
    lights switch
  use_blueprint:
    path: scene_switch.yaml
    input:
      switch_entity: switch.craft_fan_and_lights
      on_scene: scene.craft_room_switch_on
      off_scene: scene.craft_room_switch_off
- id: '1612917075093'
  alias: Family Scene Switch
  description: Turn on or off all Kitchen and Family Room lights based on the state
    of the Family Room Fan Lights
  use_blueprint:
    path: scene_switch.yaml
    input:
      switch_entity: switch.family_fan_lights
      on_scene: scene.family_room_lights_on
      off_scene: scene.family_room_lights_off
- id: '1613009569395'
  alias: Pantry Lights using Door
  description: Turn on the Pantry Lights when the Door opens, and off when the door
    closes
  use_blueprint:
    path: door_light.yaml
    input:
      door_sensor: binary_sensor.pantry_door
      target_light:
        entity_id: light.kitchen_pantry_switch
- id: '1613010337867'
  alias: Laundry Closet using Door
  description: Turn on and off the Laundry Closet lights using the door sensor
  use_blueprint:
    path: door_light.yaml
    input:
      door_sensor: binary_sensor.laundry_closet_door
      target_light:
        entity_id: light.laundry_closet_switch
- id: '1613010382531'
  alias: Master Closet using Door
  description: Turn on and off the Master Closet lights using the Door sensor
  use_blueprint:
    path: door_light.yaml
    input:
      door_sensor: binary_sensor.master_closet_door
      target_light:
        entity_id: light.master_closet_switch
- id: '1613270011215'
  alias: Guest Bathroom Bedtime Occupancy and Vacancy
  description: Guest Bathroom Lights control when bedtime is true
  use_blueprint:
    path: motion_entity.yaml
    input:
      motion_sensor: binary_sensor.guest_bath_motion
      target_entity: scene.guest_bath_night
      blocker_entity: binary_sensor.not_bedtime
      no_motion_wait: '2'
      target_off_entity: light.guest_bath_lights
- id: '1613270257631'
  alias: Boys Bath Occupancy Vacancy Daytime
  description: Boys Bath Occupancy Vacancy Daytime
  use_blueprint:
    path: motion_entity.yaml
    input:
      motion_sensor: binary_sensor.boys_bathroom_motion
      target_entity: switch.boys_bathroom_light
      blocker_entity: binary_sensor.bedtime
      no_motion_wait: 15
- id: '1613270282366'
  alias: Boys Bath Occupancy Vacancy Bedtime
  description: Boys Bath Occupancy Vacancy Bedtime
  use_blueprint:
    path: motion_entity.yaml
    input:
      motion_sensor: binary_sensor.boys_bathroom_motion
      target_entity: switch.boys_bathroom_light
      blocker_entity: binary_sensor.not_bedtime
      no_motion_wait: 5
- id: '1613270466936'
  alias: Gallery Occupancy Vacancy Daytime
  description: Gallery Occupancy Vacancy Daytime
  use_blueprint:
    path: motion_entity.yaml
    input:
      motion_sensor: binary_sensor.gallery_motion
      target_entity: scene.gallery_day_time
      blocker_entity: binary_sensor.bedtime
      no_motion_wait: '2'
      target_off_entity: switch.gallery_lights
- id: '1613270501672'
  alias: Gallery Occupancy Vacancy Bedtime
  description: Gallery Occupancy Vacancy Bedtime
  use_blueprint:
    path: motion_entity.yaml
    input:
      motion_sensor: binary_sensor.gallery_motion
      target_entity: scene.gallery_night_time
      blocker_entity: binary_sensor.not_bedtime
      no_motion_wait: '2'
      target_off_entity: switch.gallery_lights
- id: '1613270857110'
  alias: Family Room Occupancy Vacancy Bedtime
  description: Family Room Occupancy Vacancy Bedtime
  use_blueprint:
    path: motion_entity.yaml
    input:
      motion_sensor: binary_sensor.family_mantle_or_breakfast_motion
      target_entity: scene.family_night
      blocker_entity: binary_sensor.not_bedtime
      no_motion_wait: 2
      target_off_entity: switch.family_mantle_lights
- id: '1613271043951'
  alias: Laundry Occupancy Vacancy Lights
  description: ''
  use_blueprint:
    path: motion_entity.yaml
    input:
      motion_sensor: binary_sensor.laundry_motion
      target_entity: switch.laundry_lights
      no_motion_wait: '1'
- id: '1613271099858'
  alias: Garage Occupancy Vacancy Lights
  description: ''
  use_blueprint:
    path: motion_entity.yaml
    input:
      motion_sensor: binary_sensor.garage_occupancy
      target_entity: switch.garage_lights
      no_motion_wait: '10'
- id: '1613271445050'
  alias: Guest Occupancy Vacancy Daytime
  description: ''
  use_blueprint:
    path: motion_entity.yaml
    input:
      motion_sensor: binary_sensor.guest_door_motion
      target_entity: scene.guest_day
      blocker_entity: binary_sensor.bedtime
      no_motion_wait: '5'
      target_off_entity: light.guest_fan_lights
- id: '1613318531905'
  alias: Master Hall Occupancy Vacancy Daytime
  description: ''
  use_blueprint:
    path: motion_entity.yaml
    input:
      motion_sensor: binary_sensor.master_hall_motion
      target_entity: scene.master_hall_not_night
      blocker_entity: binary_sensor.bedtime
      no_motion_wait: '8'
      target_off_entity: switch.master_hall_lights
- id: '1613319635083'
  alias: Deck Occupancy Vacancy Bedtime
  description: ''
  use_blueprint:
    path: motion_entity.yaml
    input:
      motion_sensor: binary_sensor.back_door
      target_entity: scene.backyard_lights_evening_on
      blocker_entity: binary_sensor.is_light
      no_motion_wait: '5'
      target_off_entity: light.back_yard_lights
      turn_off_blocker_entity: binary_sensor.deck_field_motion
- id: '1613319734356'
  alias: Garage Lights Sunset
  description: ''
  trigger:
  - platform: sun
    event: sunset
  condition: []
  action:
  - scene: scene.garage_outdoor_lights_nighttime
  mode: single
- id: '1613319753231'
  alias: Garage Lights Sunrise
  description: ''
  trigger:
  - platform: sun
    event: sunrise
  condition: []
  action:
  - scene: scene.garage_outdoor_lights_daytime
  mode: single
- id: '1613321882329'
  alias: Front Porch Occupancy Vacancy when Dark
  description: ''
  use_blueprint:
    path: motion_entity.yaml
    input:
      motion_sensor: binary_sensor.front_porch_or_front_door_activity
      target_entity: switch.front_porch_lights
      blocker_entity: binary_sensor.is_light
      no_motion_wait: '5'
- id: '1614130827603'
  alias: Girls Hall Occupancy and Vacancy
  description: ''
  use_blueprint:
    path: motion_entity.yaml
    input:
      motion_sensor: binary_sensor.girls_hall_motion
      target_entity: switch.girls_hall_lights
      no_motion_wait: '1'
- id: '1614397013469'
  alias: Boys Hall Occupancy and Vacancy
  description: ''
  use_blueprint:
    path: motion_entity.yaml
    input:
      motion_sensor: binary_sensor.boys_hall_motion
      target_entity: switch.boys_hall_light
      no_motion_wait: '1'
- id: '1614441892945'
  alias: Game Room Night Vacancy
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.game_room_motion
    from: 'on'
    to: 'off'
    for: 00:02
  condition:
  - condition: state
    entity_id: binary_sensor.bedtime
    state: 'on'
  action:
  - scene: scene.game_room_off
  mode: single
- id: '1614914003460'
  alias: Guest Bathroom Daytime Occupancy and Vacancy
  description: Guest Bathroom Lights control when bedtime is false
  use_blueprint:
    path: motion_entity.yaml
    input:
      motion_sensor: binary_sensor.guest_bath_motion
      target_entity: scene.guest_bath_day
      blocker_entity: binary_sensor.bedtime
      no_motion_wait: 2
      target_off_entity: light.guest_bath_lights
- id: '1616254051943'
  alias: Office Lights On
  description: ''
  trigger:
  - platform: state
    entity_id: switch.office_fan_lights
    from: 'Off'
    to: 'On'
  condition: []
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.office_lamp
  mode: single
- id: '1623118222473'
  alias: Hannah Vanity Off with Room Lights
  description: ''
  trigger:
  - platform: state
    entity_id: light.hannah_bed_lightstrip
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.hannah_vanity_lights
  mode: single
- id: '1623118295643'
  alias: Heidi Vanity Off with Room Lights
  description: ''
  trigger:
  - platform: state
    entity_id: light.heidi_bed_lightstrip
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.heidi_vanity_lights
  mode: single
- id: '1623198492145'
  alias: Hannah Vanity On with Fan Lights On
  description: ''
  trigger:
  - platform: state
    entity_id: light.hannah_fan_lights
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.hannah_vanity_lights
  mode: single
- id: '1636411901610'
  alias: Craft Lights on Motion
  description: ''
  use_blueprint:
    path: motion_entity.yaml
    input:
      motion_sensor: binary_sensor.craft_motion
      target_entity: scene.craft_room_switch_on
- id: '16378828583'
  alias: Christmas Lights Nighttime
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: '30'
  condition: 
    condition: template
    value_template: "{{ now().month == 12 }}"
  action:
  - scene: scene.christmas_lights_nighttime
  mode: single
- id: '16373824590'
  alias: Christmas Lights Daytime
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: -04:00
  condition: []
  action:
  - scene: scene.christmas_lights_daytime
  mode: single
- id: '1657462874758'
  alias: Craft Lights Off with Master Lights
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.master_fan_lights
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: scene.turn_on
    data: {}
    target:
      entity_id: scene.craft_room_switch_off
  mode: single
- id: '1672327262079'
  alias: Driveway Flood Occupancy Evening
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.driveway_field_detection
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.is_dark
    state: 'on'
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.driveway_flood_on
    metadata: {}
  mode: single
- id: '1672327340724'
  alias: Driveway Flood Vacancy
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.driveway_field_detection
    to: 'off'
    for:
      hours: 0
      minutes: 10
      seconds: 0
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.driveway_flood_off
    metadata: {}
  mode: single
