homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  time_zone: !secret timezone
  customize: !include customize.yaml

# Allow IOS device autodiscovery and location tracking
#ios:
zeroconf:
# Show links to resources in log and frontend
#introduction:
# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:
# Auto-discover new or changed services
discovery: !include config/discovery.yaml
map:
updater:
config:
sun:
lovelace: 
  mode: yaml
  resources: !include config/resources.yaml
http: !include config/http.yaml
history: !include config/history.yaml
logbook: !include config/logbook.yaml
#panel_custom: !include config/panel_custom.yaml
panel_iframe: !include config/panel_iframe.yaml
frontend: !include config/frontend.yaml
cloud: !include config/cloud.yaml
#input_select: !include config/input_select.yaml
input_boolean: !include config/input_boolean.yaml
#input_text: !include config/input_text.yaml
#input_datetime: !include config/input_datetime.yaml
vacuum: !include config/vacuum.yaml
#zwave: !include config/zwave.yaml
#hue: !include config/hue.yaml
logger: !include config/logger.yaml
mqtt: !include config/mqtt.yaml
recorder: !include config/recorder.yaml
group: !include groups.yaml
cover: !include config/covers.yaml
automation: !include automations.yaml
zone: !include config/zones.yaml
sensor: !include config/sensors.yaml
binary_sensor: !include config/binary_sensors.yaml
switch: !include config/switches.yaml
scene: !include config/scenes.yaml
device_tracker: !include config/device_trackers.yaml
#media_player: !include config/media_players.yaml
light: !include config/lights.yaml
script: !include scripts.yaml
ffmpeg: !include config/ffmpeg.yaml
alarm_control_panel: !include config/alarm_control_panel.yaml
camera: !include config/camera.yaml
notify: !include config/notify.yaml
ring: !include config/ring.yaml
#abode: !include config/abode.yaml
rachio: !include config/rachio.yaml
life360: !include config/life360.yaml
#roku: !include config/roku.yaml
system_health:
#google: !include config/google.yaml

# Text to Speech
#tts: !include config/tts.yaml
