homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret timezone
  customize: !include customize.yaml
  customize_glob: !include config/customize_glob.yaml

# What is this?
#ios
# Show links to resources in log and frontend
#introduction:
# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:
# Auto-discover new or changed services
#discovery:
updater:
history:
logbook:
frontend:
config:
sun:
zwave: !include config/zwave.yaml
logger: !include config/logger.yaml
http: !include config/http.yaml
mqtt: !include config/mqtt.yaml
recorder: !include config/recorder.yaml
group: !include groups.yaml
cover: !include config/covers.yaml
automation: !include automations.yaml
zone: !include config/zones.yaml
sensor: !include config/sensors.yaml
binary_sensor: !include config/binary_sensors.yaml
switch: !include config/switches.yaml
scene: !include config/scenes.yaml
device_tracker: !include config/device_trackers.yaml
media_player: !include config/media_players.yaml
light: !include config/lights.yaml
script: !include scripts.yaml
netatmo: !include config/netatmo.yaml
# Text to Speech
#tts: !include config/tts.yaml
