# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
binary_sensor: !include config/binary_sensors.yaml
light: !include config/lights.yaml
group: !include config/groups.yaml
sensor: !include config/sensors.yaml
template: !include config/template.yaml
