resources:
  #- url: /local/plan-coordinates.js?v=1
  #  type: js
  - url: /local/mini-graph-card-bundle.js?v=0.3.0
    type: module
  - url: /local/surveillance-card.js?v=0
    type: module
  - url: /local/compact-custom-header.js?v=0.0.1
    type: module
  - url: /local/card-tools.js?v=0.0.1
    type: module
  - url: /local/popup-card.js?v=0.0.1
    type: module
views:
  - !include config/lovelace/lights.yaml
  - !include config/lovelace/alerts.yaml
  - !include config/lovelace/downstairs-security.yaml
  #- !include config/lovelace/phone.yaml
  #- !include config/lovelace/overview.yaml
  #- !include config/lovelace/downstairs_map.yaml
  #- !include config/lovelace/upstairs_map.yaml
