resources:
  - url: /local/plan-coordinates.js?v=1
    type: js
  - url: /local/mini-graph-card-bundle.js?v=0.3.0
    type: module
views:
  - !include config/lovelace/overview.yaml
  - !include config/lovelace/downstairs_map.yaml
  - !include config/lovelace/upstairs_map.yaml
