title: Upstairs Floorplan
icon: mdi:home-outline
panel: true
cards:
  - type: vertical-stack
    cards:
    - type: custom:plan-coordinates
    - type: picture-elements
      image: /local/downstairs.png
      title: Downstairs
      elements:
###############################################################################
# Stairs Elements
###############################################################################
        - type: state-icon
          entity: switch.stairs_lights
          tap_action:
            action: toggle
          style: 
            left: 34%
            top: 44.5%
            transform: scale(2, 2)
###############################################################################
# Porch Elements
###############################################################################
        - type: state-icon
          entity: switch.front_porch_lights
          tap_action:
            action: toggle
          style: 
            left: 37%
            top: 14.5%
            transform: scale(2, 2)
###############################################################################
# Entry Elements
###############################################################################
        - type: state-icon
          entity: switch.entry_lights
          tap_action:
            action: toggle
          style: 
            left: 24%
            top: 29.5%
            transform: scale(2, 2)
        - type: state-icon
          entity: switch.entry_lights
          tap_action:
            action: toggle
          style: 
            left: 24%
            top: 52%
            transform: scale(2, 2)
        - type: state-icon
          entity: light.entry_lamp
          tap_action:
            action: toggle
          style: 
            left: 48%
            top: 39%
            transform: scale(2, 2)
        - type: image
          entity: binary_sensor.entry_window_1
          filter: opacity(0.3)
          state_image:
            "on": /local/window-open.png
            "off": /local/window-closed.png
          state_filter:
            "on": opacity(1)
          style:  
            left: 35.75%
            top: 22%
        - type: image
          entity: binary_sensor.entry_window_2
          filter: opacity(0.3)
          state_image:
            "on": /local/window-open.png
            "off": /local/window-closed.png
          state_filter:
            "on": opacity(1)
          style:  
            left: 45.5%
            top: 22%
###############################################################################
# Guest Hall Elements
###############################################################################
        - type: state-icon
          entity: switch.guest_hall_lights
          tap_action:
            action: toggle
          style: 
            left: 16.5%
            top: 29.5%
            transform: scale(2, 2)
###############################################################################
# Guest Bath Elements
###############################################################################
        - type: state-icon
          entity: switch.guest_bath_lights
          tap_action:
            action: toggle
          style: 
            left: 10.75%
            top: 27.5%
            transform: scale(2, 2)
###############################################################################
# Guest Elements
###############################################################################
        - type: image
          entity: switch.guest_fan_and_lights
          tap_action:
            action: toggle
          state_image:
            "on": /local/fan.gif
            "off": /local/fan-off.png
          style: 
            left: 13%
            top: 12%
        - type: state-icon
          entity: light.guest_fan_lights
          tap_action:
            action: toggle
          hold_action:
            action: more-info
          style:
            left: 11.75%
            top: 14.5%
            transform: scale(2, 2)
        - type: image
          entity: binary_sensor.guest_window_1
          filter: opacity(0.3)
          state_image:
            "on": /local/window-open.png
            "off": /local/window-closed.png
          state_filter:
            "on": opacity(1)
          style:  
            left: 5.75%
            top: 1.25%
            transform: rotate(-45deg)
        - type: image
          entity: binary_sensor.guest_window_2
          filter: opacity(0.3)
          state_image:
            "on": /local/window-open.png
            "off": /local/window-closed.png
          state_filter:
            "on": opacity(1)
          style:  
            left: 11.25%
            top: 1%
        - type: image
          entity: binary_sensor.guest_window_3
          filter: opacity(0.3)
          state_image:
            "on": /local/window-open.png
            "off": /local/window-closed.png
          state_filter:
            "on": opacity(1)
          style:  
            left: 13.75% 
            top: 1.25%
            transform: rotate(45deg)

###############################################################################
# Dining Room Elements
###############################################################################
###############################################################################
# Family Room Elements
###############################################################################
###############################################################################
# Kitchen Room Elements
###############################################################################
###############################################################################
# Breakfast Room Elements
###############################################################################
