title: Downstairs Floorplan
icon: mdi:shield-home
panel: true
cards:
  - type: picture-elements
    image: /local/images/downstairs-security-map.png
    #title: Downstairs
    elements:
###############################################################################
# Outdoor Camera Motion
###############################################################################
      - type: image
        entity: binary_sensor.driveway_motion
        filter: opacity(0)
        image: /local/images/driveway-motion.png
        state_filter:
          "on": opacity(1)
        style: 
          left: 0%
          top: 0%
          transform: none
      - type: image
        entity: binary_sensor.back_gate_yard_motion
        filter: opacity(0)
        image: /local/images/back-gate-yard-motion.png
        state_filter:
          "on": opacity(1)
        style: 
          left: 0%
          top: 0%
          transform: none
      - type: image
        entity: binary_sensor.back_garden_motion
        filter: opacity(0)
        image: /local/images/garden-yard-motion.png
        state_filter:
          "on": opacity(1)
        style: 
          left: 0%
          top: 0%
          transform: none
      - type: image
        entity: binary_sensor.garden_side_yard_motion
        filter: opacity(0)
        image: /local/images/garden-side-yard-motion.png
        state_filter:
          "on": opacity(1)
        style: 
          left: 0%
          top: 0%
          transform: none
      - type: image
        entity: binary_sensor.playscape_motion
        filter: opacity(0)
        image: /local/images/playscape-motion.png
        state_filter:
          "on": opacity(1)
        style: 
          left: 0%
          top: 0%
          transform: none
      - type: image
        entity: binary_sensor.deck_motion
        filter: opacity(0)
        image: /local/images/deck-motion.png
        state_filter:
          "on": opacity(1)
        style: 
          left: 0%
          top: 0%
          transform: none
      - type: image
        entity: binary_sensor.pool_motion
        filter: opacity(0)
        image: /local/images/pool-motion.png
        state_filter:
          "on": opacity(1)
        style: 
          left: 0%
          top: 0%
          transform: none
      - type: image
        entity: binary_sensor.gate_side_yard_motion
        filter: opacity(0)
        image: /local/images/gate-side-yard-motion.png
        state_filter:
          "on": opacity(1)
        style: 
          left: 0%
          top: 0%
          transform: none
      - type: image
        entity: binary_sensor.front_porch_motion
        filter: opacity(0)
        image: /local/images/front-porch-motion.png
        state_filter:
          "on": opacity(1)
        style: 
          left: 0%
          top: 0%
          transform: none
      - type: image
        entity: binary_sensor.front_yard_motion
        filter: opacity(0)
        image: /local/images/front-yard-motion.png
        state_filter:
          "on": opacity(1)
        style: 
          left: 0%
          top: 0%
          transform: none
###############################################################################
# Indoor Downstairs Motion
###############################################################################
###############################################################################
# Indoor Downstairs Motion
###############################################################################
