title: Downstairs Floorplan
icon: mdi:shield-home
panel: true
cards:
  - type: picture-elements
    image: /local/images/downstairs-security.png
    #title: Downstairs
    elements:
###############################################################################
# Outdoor Camera Motion
###############################################################################
      - type: image
        entity: binary_sensor.driveway_motion
        filter: opacity(0)
        image: /local/images/driveway-motion.png
        tap_action:
          action: none
        hold_action:
          action: none
        state_filter:
          "on": opacity(1)
        style: 
          left: 0%
          top: 0%
          transform: none
      - type: image
        entity: binary_sensor.back_gate_yard_motion
        filter: opacity(0)
        image: /local/images/back-gate-yard-motion.png
        tap_action:
          action: none
        hold_action:
          action: none
        state_filter:
          "on": opacity(1)
        style: 
          left: 0%
          top: 0%
          transform: none
      - type: image
        entity: binary_sensor.back_garden_motion
        filter: opacity(0)
        image: /local/images/garden-yard-motion.png
        tap_action:
          action: none
        hold_action:
          action: none
        state_filter:
          "on": opacity(1)
        style: 
          left: 0%
          top: 0%
          transform: none
      - type: image
        entity: binary_sensor.garden_side_only_motion
        filter: opacity(0)
        image: /local/images/garden-side-yard-motion.png
        tap_action:
          action: none
        hold_action:
          action: none
        state_filter:
          "on": opacity(1)
        style: 
          left: 0%
          top: 0%
          transform: none
      - type: image
        entity: binary_sensor.playscape_motion
        filter: opacity(0)
        image: /local/images/playscape-motion.png
        tap_action:
          action: none
        hold_action:
          action: none
        state_filter:
          "on": opacity(1)
        style: 
          left: 0%
          top: 0%
          transform: none
      - type: image
        entity: binary_sensor.deck_motion
        filter: opacity(0)
        image: /local/images/deck-motion.png
        tap_action:
          action: none
        hold_action:
          action: none
        state_filter:
          "on": opacity(1)
        style: 
          left: 0%
          top: 0%
          transform: none
      - type: image
        entity: binary_sensor.pool_motion
        filter: opacity(0)
        image: /local/images/pool-motion.png
        tap_action:
          action: none
        hold_action:
          action: none
        state_filter:
          "on": opacity(1)
        style: 
          left: 0%
          top: 0%
          transform: none
      - type: image
        entity: binary_sensor.gate_side_yard_motion
        filter: opacity(0)
        image: /local/images/gate-side-yard-motion.png
        tap_action:
          action: none
        hold_action:
          action: none
        state_filter:
          "on": opacity(1)
        style: 
          left: 0%
          top: 0%
          transform: none
      - type: image
        entity: binary_sensor.front_porch_motion
        filter: opacity(0)
        image: /local/images/front-porch-motion.png
        tap_action:
          action: none
        hold_action:
          action: none
        state_filter:
          "on": opacity(1)
        style: 
          left: 0%
          top: 0%
          transform: none
      - type: image
        entity: binary_sensor.front_guest_only_motion
        filter: opacity(0)
        image: /local/images/front-yard-motion.png
        tap_action:
          action: none
        hold_action:
          action: none
        state_filter:
          "on": opacity(1)
        style: 
          left: 0%
          top: 0%
          transform: none
      - type: image
        entity: binary_sensor.garden_side_and_front_guest_motion
        filter: opacity(0)
        image: /local/images/garden-side-and-front-guest-motion.png
        tap_action:
          action: none
        hold_action:
          action: none
        state_filter:
          "on": opacity(1)
        style: 
          left: 0%
          top: 0%
          transform: none
###############################################################################
# Camera Graphics
###############################################################################
      - type: image
        image: /local/images/deck-camera.png
        tap_action:
          action: none
        hold_action:
          action: none
        style: 
          left: 0%
          top: 0%
          transform: none
      - type: image
        image: /local/images/driveway-camera.png
        tap_action:
          action: none
        hold_action:
          action: none
        style: 
          left: 0%
          top: 0%
          transform: none
      - type: image
        image: /local/images/garden-back-yard-camera.png
        tap_action:
          action: none
        hold_action:
          action: none
        style: 
          left: 0%
          top: 0%
          transform: none
      - type: image
        image: /local/images/garden-side-yard-camera.png
        tap_action:
          action: none
        hold_action:
          action: none
        style: 
          left: 0%
          top: 0%
          transform: none
      - type: image
        image: /local/images/gate-back-yard-camera.png
        tap_action:
          action: none
        hold_action:
          action: none
        style: 
          left: 0%
          top: 0%
          transform: none
      - type: image
        image: /local/images/gate-side-yard-camera.png
        tap_action:
          action: none
        hold_action:
          action: none
        style: 
          left: 0%
          top: 0%
          transform: none
      - type: image
        image: /local/images/guest-front-yard-camera.png
        tap_action:
          action: none
        hold_action:
          action: none
        style: 
          left: 0%
          top: 0%
          transform: none
      - type: image
        image: /local/images/playscape-camera.png
        tap_action:
          action: none
        hold_action:
          action: none
        style: 
          left: 0%
          top: 0%
          transform: none
      - type: image
        image: /local/images/pool-camera.png
        tap_action:
          action: none
        hold_action:
          action: none
        style: 
          left: 0%
          top: 0%
          transform: none
      - type: image
        image: /local/images/front-porch-camera.png
        tap_action:
          action: none
        hold_action:
          action: none
        style: 
          left: 0%
          top: 0%
          transform: none
###############################################################################
# Camera Clickable Overlays
###############################################################################
###############################################################################
# Indoor Downstairs Motion
###############################################################################
