title: Downstairs Floorplan
icon: mdi:shield-home
panel: true
cards:
  - type: picture-elements
    image: /local/images/downstairs-security.png
    #title: Downstairs
    elements:
###############################################################################
# Outdoor Camera Motion
###############################################################################
      - type: image
        #entity: binary_sensor.driveway_only_motion
        entity: binary_sensor.driveway_motion
        filter: opacity(0)
        image: /local/images/driveway-motion.png
        tap_action:
          action: none
        hold_action:
          action: none
        state_filter:
          "on": opacity(1)
        style: 
          left: 0%
          top: 0%
          z-index: 10
          transform: none
      - type: image
        entity: binary_sensor.back_gate_yard_motion
        filter: opacity(0)
        image: /local/images/back-gate-motion.png
        tap_action:
          action: none
        hold_action:
          action: none
        state_filter:
          "on": opacity(1)
        style: 
          left: 0%
          top: 0%
          z-index: 10
          transform: none
      - type: image
        entity: binary_sensor.pool_and_back_gate_motion
        filter: opacity(0)
        image: /local/images/pool-and-back-gate-motion.png
        tap_action:
          action: none
        hold_action:
          action: none
        state_filter:
          "on": opacity(1)
        style: 
          left: 0%
          top: 0%
          z-index: 10
          transform: none
      - type: image
        entity: binary_sensor.back_garden_motion
        filter: opacity(0)
        image: /local/images/garden-yard-motion.png
        tap_action:
          action: none
        hold_action:
          action: none
        state_filter:
          "on": opacity(1)
        style: 
          left: 0%
          top: 0%
          z-index: 10
          transform: none
      - type: image
        entity: binary_sensor.garden_side_and_front_guest_motion
        filter: opacity(0)
        image: /local/images/garden-side-and-front-guest-motion.png
        tap_action:
          action: none
        hold_action:
          action: none
        state_filter:
          "on": opacity(1)
        style: 
          left: 0%
          top: 0%
          z-index: 10
          transform: none
      - type: image
        entity: binary_sensor.guest_front_and_driveway_motion
        filter: opacity(0)
        image: /local/images/guest-front-and-driveway-motion.png
        tap_action:
          action: none
        hold_action:
          action: none
        state_filter:
          "on": opacity(1)
        style: 
          left: 0%
          top: 0%
          z-index: 10
          transform: none
      - type: image
        # Use this if you want only this region when the neighbor fires too
        #entity: binary_sensor.garden_side_only_motion
        entity: binary_sensor.garden_side_yard_motion
        filter: opacity(0)
        image: /local/images/garden-side-yard-motion.png
        tap_action:
          action: none
        hold_action:
          action: none
        state_filter:
          "on": opacity(1)
        style: 
          left: 0%
          top: 0%
          z-index: 10
          transform: none
      - type: image
        entity: binary_sensor.playscape_motion
        filter: opacity(0)
        image: /local/images/playscape-motion.png
        tap_action:
          action: none
        hold_action:
          action: none
        state_filter:
          "on": opacity(1)
        style: 
          left: 0%
          top: 0%
          z-index: 10
          transform: none
      - type: image
        entity: binary_sensor.deck_motion
        filter: opacity(0)
        image: /local/images/deck-motion.png
        tap_action:
          action: none
        hold_action:
          action: none
        state_filter:
          "on": opacity(1)
        style: 
          left: 0%
          top: 0%
          z-index: 10
          transform: none
      - type: image
        entity: binary_sensor.deck_and_pool_motion
        filter: opacity(0)
        image: /local/images/deck-and-pool-motion.png
        tap_action:
          action: none
        hold_action:
          action: none
        state_filter:
          "on": opacity(1)
        style: 
          left: 0%
          top: 0%
          z-index: 10
          transform: none
      - type: image
        entity: binary_sensor.pool_motion
        filter: opacity(0)
        image: /local/images/pool-motion.png
        tap_action:
          action: none
        hold_action:
          action: none
        state_filter:
          "on": opacity(1)
        style: 
          left: 0%
          top: 0%
          z-index: 10
          transform: none
      - type: image
        entity: binary_sensor.gate_side_yard_motion
        filter: opacity(0)
        image: /local/images/gate-side-yard-motion.png
        tap_action:
          action: none
        hold_action:
          action: none
        state_filter:
          "on": opacity(1)
        style: 
          left: 0%
          top: 0%
          z-index: 10
          transform: none
      - type: image
        entity: binary_sensor.front_porch_motion
        filter: opacity(0)
        image: /local/images/front-porch-motion.png
        tap_action:
          action: none
        hold_action:
          action: none
        state_filter:
          "on": opacity(1)
        style: 
          left: 0%
          top: 0%
          z-index: 10
          transform: none
      - type: image
        # Use this if you want only this region when the neighbor fires too
        #entity: binary_sensor.front_guest_only_motion
        entity: binary_sensor.front_yard_motion
        filter: opacity(0)
        image: /local/images/guest-front-motion.png
        tap_action:
          action: none
        hold_action:
          action: none
        state_filter:
          "on": opacity(1)
        style: 
          left: 0%
          top: 0%
          z-index: 10
          transform: none
      - type: image
        # Use this if you want only this region when the neighbor fires too
        #entity: binary_sensor.garden_side_only_motion
        entity: binary_sensor.garden_side_yard_motion
        filter: opacity(0)
        image: /local/images/garden-side-yard-motion.png
        tap_action:
          action: none
        hold_action:
          action: none
        state_filter:
          "on": opacity(1)
        style: 
          left: 0%
          top: 0%
          z-index: 10
          transform: none
      - type: image
        entity: binary_sensor.playscape_motion
        filter: opacity(0)
        image: /local/images/playscape-motion.png
        tap_action:
          action: none
        hold_action:
          action: none
        state_filter:
          "on": opacity(1)
        style: 
          left: 0%
          top: 0%
          z-index: 10
          transform: none
      - type: image
        entity: binary_sensor.deck_motion
        filter: opacity(0)
        image: /local/images/deck-motion.png
        tap_action:
          action: none
        hold_action:
          action: none
        state_filter:
          "on": opacity(1)
        style: 
          left: 0%
          top: 0%
          z-index: 10
          transform: none
      - type: image
        entity: binary_sensor.pool_motion
        filter: opacity(0)
        image: /local/images/pool-motion.png
        tap_action:
          action: none
        hold_action:
          action: none
        state_filter:
          "on": opacity(1)
        style: 
          left: 0%
          top: 0%
          z-index: 10
          transform: none
      - type: image
        entity: binary_sensor.gate_side_yard_motion
        filter: opacity(0)
        image: /local/images/gate-side-yard-motion.png
        tap_action:
          action: none
        hold_action:
          action: none
        state_filter:
          "on": opacity(1)
        style: 
          left: 0%
          top: 0%
          z-index: 10
          transform: none
      - type: image
        entity: binary_sensor.front_porch_motion
        filter: opacity(0)
        image: /local/images/front-porch-motion.png
        tap_action:
          action: none
        hold_action:
          action: none
        state_filter:
          "on": opacity(1)
        style: 
          left: 0%
          top: 0%
          z-index: 10
          transform: none
      - type: image
        # Use this if you want only this region when the neighbor fires too
        #entity: binary_sensor.front_guest_only_motion
        entity: binary_sensor.front_yard_motion
        filter: opacity(0)
        image: /local/images/guest-front-motion.png
        tap_action:
          action: none
        hold_action:
          action: none
        state_filter:
          "on": opacity(1)
        style: 
          left: 0%
          top: 0%
          z-index: 10
          transform: none
      - type: image
        entity: binary_sensor.garden_side_and_front_guest_motion
        filter: opacity(0)
        image: /local/images/garden-side-and-front-guest-motion.png
        tap_action:
          action: none
        hold_action:
          action: none
        state_filter:
          "on": opacity(1)
        style: 
          left: 0%
          top: 0%
          z-index: 10
          transform: none
###############################################################################
# Camera Icons
###############################################################################
      - type: image
        image: /local/images/outdoor-security-camera-icons.png
        tap_action:
          action: none
        hold_action:
          action: none
        style: 
          left: 0%
          top: 0%
          z-index: 20
          transform: none
###############################################################################
# Camera Clickable Overlays
###############################################################################
      # Driveway Camera Clickable Overlay
      - type: image
        image: /local/images/camera-button-overlay.png
        #image: /local/images/camera-button-overlay-visible.png
        tap_action:
          action: none
        hold_action:
          action: none
        style: 
          height: 3.81%
          width: 3.33%
          left: 83.8%
          top: 18%
          z-index: 30
          transform: none
      # Guest Front Camera Clickable Overlay
      - type: image
        image: /local/images/camera-button-overlay.png
        #image: /local/images/camera-button-overlay-visible.png
        tap_action:
          action: none
        hold_action:
          action: none
        style: 
          height: 3.81%
          width: 3.33%
          left: 12.1%
          top: 18.15%
          z-index: 30
          transform: none
      # Front Porch Camera Clickable Overlay
      - type: image
        image: /local/images/camera-button-overlay.png
        #image: /local/images/camera-button-overlay-visible.png
        tap_action:
          action: none
        hold_action:
          action: none
        style: 
          height: 3.81%
          width: 3.33%
          left: 47.35%
          top: 30.5%
          z-index: 30
          transform: none
      # Gate Side Yard Clickable Overlay
      - type: image
        image: /local/images/camera-button-overlay.png
        #image: /local/images/camera-button-overlay-visible.png
        tap_action:
          action: none
        hold_action:
          action: none
        style: 
          height: 3.81%
          width: 3.33%
          left: 87.3%
          top: 37.15%
          z-index: 30
          transform: none
      # Gate Back Yard Clickable Overlay
      - type: image
        image: /local/images/camera-button-overlay.png
        #image: /local/images/camera-button-overlay-visible.png
        tap_action:
          action: none
        hold_action:
          action: none
        style: 
          height: 3.81%
          width: 3.33%
          left: 78.96%
          top: 73.5%
          z-index: 30
          transform: none
      # Pool Clickable Overlay
      - type: image
        image: /local/images/camera-button-overlay.png
        #image: /local/images/camera-button-overlay-visible.png
        tap_action:
          action: none
        hold_action:
          action: none
        style: 
          height: 3.81%
          width: 3.33%
          left: 74.8%
          top: 77.5%
          z-index: 30
          transform: none
      # Deck Clickable Overlay
      - type: image
        image: /local/images/camera-button-overlay.png
        #image: /local/images/camera-button-overlay-visible.png
        tap_action:
          action: none
        hold_action:
          action: none
        style: 
          height: 3.81%
          width: 3.33%
          left: 29.95%
          top: 77.02%
          z-index: 30
          transform: none
      # Playscape Clickable Overlay
      - type: image
        image: /local/images/camera-button-overlay.png
        #image: /local/images/camera-button-overlay-visible.png
        tap_action:
          action: none
        hold_action:
          action: none
        style: 
          height: 3.81%
          width: 3.33%
          left: 13.2%
          top: 77.75%
          z-index: 30
          transform: none
      # Garden Back Yard Clickable Overlay
      - type: image
        image: /local/images/camera-button-overlay.png
        #image: /local/images/camera-button-overlay-visible.png
        tap_action:
          action: none
        hold_action:
          action: none
        style: 
          height: 3.81%
          width: 3.33%
          left: 9.1%
          top: 74%
          z-index: 30
          transform: none
      # Garden Side Yard Clickable Overlay
      - type: image
        image: /local/images/camera-button-overlay.png
        #image: /local/images/camera-button-overlay-visible.png
        tap_action:
          action: none
        hold_action:
          action: none
        style: 
          height: 3.81%
          width: 3.33%
          left: 10.4%
          top: 41.65%
          z-index: 30
          transform: none
###############################################################################
# Indoor Downstairs Motion
###############################################################################
      - type: image
        entity: binary_sensor.breakfast_motion
        filter: opacity(0)
        image: /local/images/breakfast-motion.png
        tap_action:
          action: none
        hold_action:
          action: none
        state_filter:
          "on": opacity(1)
        style: 
          left: 0%
          top: 0%
          z-index: 10
          transform: none
      - type: image
        entity: binary_sensor.family_mantle_motion
        filter: opacity(0)
        image: /local/images/family-motion.png
        tap_action:
          action: none
        hold_action:
          action: none
        state_filter:
          "on": opacity(1)
        style: 
          left: 0%
          top: 0%
          z-index: 10
          transform: none
      - type: image
        entity: binary_sensor.family_mantle_and_breakfast_motion
        filter: opacity(0)
        image: /local/images/breakfast-and-family-motion.png
        tap_action:
          action: none
        hold_action:
          action: none
        state_filter:
          "on": opacity(1)
        style: 
          left: 0%
          top: 0%
          z-index: 10
          transform: none
      - type: image
        entity: binary_sensor.craft_motion
        filter: opacity(0)
        image: /local/images/craft-motion.png
        tap_action:
          action: none
        hold_action:
          action: none
        state_filter:
          "on": opacity(1)
        style: 
          left: 0%
          top: 0%
          z-index: 10
          transform: none
      - type: image
        entity: binary_sensor.dining_motion
        filter: opacity(0)
        image: /local/images/dining-motion.png
        tap_action:
          action: none
        hold_action:
          action: none
        state_filter:
          "on": opacity(1)
        style: 
          left: 0%
          top: 0%
          z-index: 10
          transform: none
      - type: image
        entity: binary_sensor.stairs_motion
        filter: opacity(0)
        image: /local/images/stairs-motion.png
        tap_action:
          action: none
        hold_action:
          action: none
        state_filter:
          "on": opacity(1)
        style: 
          left: 0%
          top: 0%
          z-index: 10
          transform: none
      - type: image
        entity: binary_sensor.entry_motion
        filter: opacity(0)
        image: /local/images/entry-motion.png
        tap_action:
          action: none
        hold_action:
          action: none
        state_filter:
          "on": opacity(1)
        style: 
          left: 0%
          top: 0%
          z-index: 10
          transform: none
      - type: image
        entity: binary_sensor.dining_and_stairs_motion
        filter: opacity(0)
        image: /local/images/dining-and-stairs-motion.png
        tap_action:
          action: none
        hold_action:
          action: none
        state_filter:
          "on": opacity(1)
        style: 
          left: 0%
          top: 0%
          z-index: 10
          transform: none
      - type: image
        entity: binary_sensor.garage_motion
        filter: opacity(0)
        image: /local/images/garage-motion.png
        tap_action:
          action: none
        hold_action:
          action: none
        state_filter:
          "on": opacity(1)
        style: 
          left: 0%
          top: 0%
          z-index: 10
          transform: none
      - type: image
        entity: binary_sensor.guest_bath_motion
        filter: opacity(0)
        image: /local/images/guest-bath-motion.png
        tap_action:
          action: none
        hold_action:
          action: none
        state_filter:
          "on": opacity(1)
        style: 
          left: 0%
          top: 0%
          z-index: 10
          transform: none

###############################################################################
# Indoor Downstairs Doors
###############################################################################
###############################################################################
# Indoor Downstairs Windows
###############################################################################
