title: Lights
icon: mdi:lightbulb
cards:
  - type: vertical-stack
    show-header: false
    cards:
      - type: entity-filter
        name: Non-Bedroom Lights
        show_state: false
        entities: 

