title: Phone Overview
icon: mdi:cellphone-iphone
cards:
  - type: custom:compact-custom-header
    menu: false
    options: false
    voice: false
    notification: false
  - type: vertical-stack
    show-header: false
    popup_cards:
      group.all_lights:
        title: All Lights Options
        card:
          type: entities
          entities:
            - light.gallery
            - light.office_fan
    cards:
      - type: glance
        show_state: false
        entities:
          - entity: group.all_lights
            name: Lights
            tap_action:
              action: toggle
