title: Upstairs Floorplan
icon: mdi:home-outline
panel: true
cards:
  - type: vertical-stack
    cards:
    - type: picture-elements
      image: /local/upstairs.svg
      title: Upstairs
      elements:
###############################################################################
# Office Elements
###############################################################################
        - type: state-icon
          entity: light.office_fan_lights
          tap_action:
            action: toggle
          hold_action:
            action: more-info
          style: 
            left: 82.75%
            top: 78.5%
            transform: scale(2, 2)
        - type: image
          entity: switch.office_fan
          tap_action:
            action: toggle
          state_image:
            "on": /local/fan.gif
            "off": /local/fan-off.png
          style: 
            left: 84%
            top: 75%
        - type: image
          entity: switch.office_heater
          tap_action:
            action: toggle
          state_image:
            "on": /local/radiator-on.png
            "off": /local/radiator-off.png
          style:
            left: 95%
            top: 96%
        - type: state-icon
          entity: switch.office_lamp
          tap_action:
            action: toggle
          hold_action:
            action: more-info
          style: 
            left: 68.75%
            top: 95%
            transform: scale(2, 2)
        - type: image
          entity: binary_sensor.office_window_1
          filter: opacity(0.3)
          state_image:
            "on": /local/window-open.png
            "off": /local/window-closed.png
          state_filter:
            "on": opacity(1)
          style:  
            left: 92%
            top: 98%
        - type: image
          entity: binary_sensor.office_window_2
          filter: opacity(0.3)
          state_image:
            "on": /local/window-open.png
            "off": /local/window-closed.png
          state_filter:
            "on": opacity(1)
          style:  
            left: 76%
            top: 98%
        - type: state-icon
          entity: light.office_go
          tap_action:
            action: toggle
          hold_action:
            action: more-info
          style:
            left: 95.5%
            top: 91%
            transform: scale(2, 2)
        - type: state-label
          entity: sensor.office_temperature
          suffix: "F"
          style:
            left: 71%
            top: 60%
            text-align: left
        - type: state-label
          entity: sensor.office_humidity
          suffix: "%"
          style:
            left: 71%
            top: 61.5%
            text-align: left
###############################################################################
# Boy's Hall Elements
###############################################################################
        - type: state-icon
          entity: switch.boys_hall_light
          tap_action:
            action: toggle
          style:
            left: 78%
            top: 48%
            transform: scale(2, 2)
###############################################################################
# Boy's Bathroom Elements
###############################################################################
        - type: state-icon
          entity: switch.boys_bathroom_light
          tap_action:
            action: toggle
          style:
            left: 84%
            top: 49.5%
            transform: scale(2, 2)
###############################################################################
# Noah's Room Elements
###############################################################################
        - type: state-label
          entity: sensor.noah_multisensor_temperature
          style:
            left: 74.5%
            top: 23%
            text-align: left
        - type: state-label
          entity: sensor.noah_multisensor_humidity
          style:
            left: 74.5%
            top: 24.5%
            text-align: left
        - type: image
          entity: binary_sensor.noah_room_window_2
          filter: opacity(0.3)
          state_image:
            "on": /local/window-open.png
            "off": /local/window-closed.png
          state_filter:
            "on": opacity(1)
          style:  
            left: 88.5%
            top: 2%
        - type: state-icon
          entity: light.noah_lamp
          tap_action:
            action: toggle
          hold_action:
            action: more-info
          style:
            left: 72.75%
            top: 18%
            transform: scale(2, 2)
        - type: state-icon
          entity: light.noah_bed_lightstrip
          tap_action:
            action: toggle
          hold_action:
            action: more-info
          style:
            left: 95%
            top: 12%
            transform: scale(2, 2)
        - type: state-icon
          entity: light.noah_fan_lights
          tap_action:
            action: toggle
          hold_action:
            action: more-info
          style:
            left: 85%
            top: 20%
            transform: scale(2, 2)
###############################################################################
# Gallery Elements
###############################################################################
        - type: state-icon
          entity: switch.gallery_lights
          tap_action:
            action: toggle
          style: 
            left: 48.50%
            top: 48%
            transform: scale(2, 2)
###############################################################################
# Girl's Hall Elements
###############################################################################
        - type: state-icon
          entity: switch.girls_hall_lights
          tap_action:
            action: toggle
          style:
            right: 70%
            top: 52%
            transform: scale(2, 2)
###############################################################################
# Game Room Elements
###############################################################################
        - type: state-icon
          entity: light.game_room_fan
          tap_action:
            action: toggle
          hold_action:
            action: more-info
          style: 
            left: 48.75%
            top: 78.5%
            transform: scale(2, 2)
        - type: image
          entity: switch.game_room_fan
          tap_action:
            action: toggle
          state_image:
            "on": /local/fan.gif
            "off": /local/fan-off.png
          style: 
            left: 50%
            top: 75%
        - type: image
          entity: binary_sensor.game_room_window_1
          filter: opacity(0.3)
          state_image:
            "on": /local/window-open.png
            "off": /local/window-closed.png
          state_filter:
            "on": opacity(1)
          style:  
            left: 57.75%
            top: 98%
        - type: image
          entity: binary_sensor.game_room_window_2
          filter: opacity(0.3)
          state_image:
            "on": /local/window-open.png
            "off": /local/window-closed.png
          state_filter:
            "on": opacity(1)
          style:  
            left: 50%
            top: 98%
        - type: image
          entity: binary_sensor.game_room_window_3
          filter: opacity(0.3)
          state_image:
            "on": /local/window-open.png
            "off": /local/window-closed.png
          state_filter:
            "on": opacity(1)
          style:  
            left: 42%
            top: 98%
###############################################################################
# Stairs Elements
###############################################################################
        - type: state-icon
          entity: switch.stairs_lights
          tap_action:
            action: toggle
          style: 
            left: 48.50%
            top: 35%
            transform: scale(2, 2)
###############################################################################
# Hannah's Room Elements
###############################################################################
        - type: state-label
          entity: sensor.hannah_multisensor_temperature
          style:
            left: 4%
            top: 74%
            text-align: left
        - type: state-label
          entity: sensor.hannah_multisensor_humidity
          style:
            left: 4%
            top: 75.5%
            text-align: left
        - type: state-icon
          entity: light.hannah_fan_lights
          tap_action:
            action: toggle
          hold_action:
            action: more-info
          style: 
            left: 14%
            top: 78.5%
            transform: scale(2, 2)
        - type: state-icon
          entity: light.hannah_lamp
          tap_action:
            action: toggle
          hold_action:
            action: more-info
          style: 
            left: 3%
            top: 92%
            transform: scale(2, 2)
        - type: state-icon
          entity: light.hannah_bed_lightstrip
          tap_action:
            action: toggle
          hold_action:
            action: more-info
          style: 
            left: 19%
            top: 93%
            transform: scale(2, 2)
        - type: image
          entity: binary_sensor.hannah_window_1
          filter: opacity(0.3)
          state_image:
            "on": /local/window-open.png
            "off": /local/window-closed.png
          state_filter:
            "on": opacity(1)
          style:  
            left: 5.5%
            top: 95.75%
        - type: image
          entity: binary_sensor.hannah_window_2
          filter: opacity(0.3)
          state_image:
            "on": /local/window-open.png
            "off": /local/window-closed.png
          state_filter:
            "on": opacity(1)
          style:  
            left: 2%
            top: 92%
###############################################################################
# Heidi's Room Elements
###############################################################################
        - type: state-label
          entity: sensor.heidi_multisensor_temperature
          style:
            left: 26%
            top: 15%
            text-align: left
        - type: state-label
          entity: sensor.heidi_multisensor_humidity
          style:
            left: 26%
            top: 16.5%
            text-align: left
        - type: image
          entity: switch.heidi_heater
          tap_action:
            action: toggle
          state_image:
            "on": /local/radiator-on.png
            "off": /local/radiator-off.png
          style:
            left: 28%
            top: 28%
        - type: state-icon
          entity: light.heidi_bed_lightstrip
          tap_action:
            action: toggle
          hold_action:
            action: more-info
          style: 
            left: 10.5%
            top: 5.5%
            transform: scale(2, 2)
        - type: state-icon
          entity: light.heidi_fan_lights
          tap_action:
            action: toggle
          hold_action:
            action: more-info
          style: 
            left: 13.75%
            top: 23%
            transform: scale(2, 2)
        - type: image
          entity: switch.heidi_fan_and_lights
          tap_action:
            action: toggle
          state_image:
            "on": /local/fan.gif
            "off": /local/fan-off.png
          style: 
            left: 15%
            top: 21%
        - type: image
          entity: binary_sensor.heidi_window_1
          filter: opacity(0.3)
          state_image:
            "on": /local/window-open.png
            "off": /local/window-closed.png
          state_filter:
            "on": opacity(1)
          style:  
            left: 2%
            top: 27.75%
        - type: image
          entity: binary_sensor.heidi_window_2
          filter: opacity(0.3)
          state_image:
            "on": /local/window-open.png
            "off": /local/window-closed.png
          state_filter:
            "on": opacity(1)
          style:  
            left: 2%
            top: 9.75%
