- platform: template
  sensors:
    cpu_overload:
      friendly_name: 'CPU Above 25%'
      value_template: >-
        {%- if states('sensor.cpu_use')|int >= 25 -%}
          True
        {%- else -%}
          False
        {%- endif -%}
      entity_id:
        - sensor.cpu_use
#      value_template: "{{ states('sensor.cpu_use')|int >= 25 }}"

- platform: template
  sensors:
    guest_occupancy:
      friendly_name: 'Guest Occupancy'
      value_template: >-
        {%- if is_state("sensor.guest_fan_and_lights_burglar", "8")
            or is_state("sensor.guest_multisensor_burglar", "8") -%}
          True
        {%- else -%}
          False
        {%- endif -%}
      entity_id:
        - sensor.guest_fan_and_lights_burglar
        - sensor.guest_multisensor_burglar

- platform: template
  sensors:
    laundry_room_occupancy:
      friendly_name: 'Laundry Room Occupancy'
      value_template: >-
        {%- if is_state("sensor.laundry_room_lights_burglar", "8") -%}
          True
        {%- else -%}
          False
        {%- endif -%}
      entity_id:
        - sensor.laundry_room_lights_burglar

- platform: template
  sensors:
    master_hall_occupancy:
      friendly_name: 'Master Hall Occupancy'
      value_template: >-
        {%- if is_state("sensor.master_hall_lights_burglar", "8")
            or is_state("sensor.stairs_light_burglar", "8") -%}
          True
        {%- else -%}
          False
        {%- endif -%}
      entity_id:
        - sensor.master_hall_lights_burglar
        - sensor.stairs_light_burglar

- platform: template
  sensors:
    gallery_occupancy:
      friendly_name: 'Gallery Occupancy'
      value_template: >-
        {%- if is_state("sensor.gallery_hall_lights_burglar", "8")
            or is_state("sensor.gallery_hsm200_burglar", "7") -%}
          True
        {%- else -%}
          False
        {%- endif -%}
      entity_id:
        - sensor.gallery_hall_lights_burglar
        - sensor.gallery_hsm200_burglar

- platform: template
  sensors:
    game_room_occupancy:
      friendly_name: 'Game Room Occupancy'
      value_template: >-
        {%- if is_state("sensor.game_room_fan_burglar", "8") -%}
          True
        {%- else -%}
          False
        {%- endif -%}
      entity_id:
        - sensor.game_room_fan_burglar


- platform: template
  sensors:
    master_closet_door:
      friendly_name: 'Master Closet Door'
      value_template: >-
        {%- if is_state("sensor.master_closet_door_access_control", "22") -%}
          True
        {%- else -%}
          False
        {%- endif -%}
      entity_id:
        - sensor.master_closet_door_access_control
