- platform: ring
  monitored_conditions:
    - ding
    - motion

- platform: template
  sensors:
    guest_occupancy:
      friendly_name: 'Guest Occupancy'
      value_template: >-
        {%- if is_state("sensor.guest_fan_and_lights_burglar", "8") -%}
          True
        {%- else -%}
          False
        {%- endif -%}

- platform: template
  sensors:
    guest_bathroom_occupancy:
      friendly_name: 'Guest Bathroom Occupancy'
      value_template: >-
        {%- if is_state("sensor.guest_bathroom_lights_burglar", "8") -%}
          True
        {%- else -%}
          False
        {%- endif -%}

- platform: template
  sensors:
    dining_room_occupancy:
      friendly_name: 'Dining Occupancy'
      value_template: >-
        {%- if is_state("sensor.dining_room_lights_burglar", "8") -%}
          True
        {%- else -%}
          False
        {%- endif -%}

- platform: template
  sensors:
    laundry_room_occupancy:
      friendly_name: 'Laundry Room Occupancy'
      value_template: >-
        {%- if is_state("sensor.laundry_room_lights_burglar", "8") -%}
          True
        {%- else -%}
          False
        {%- endif -%}

- platform: template
  sensors:
    master_occupancy:
      friendly_name: 'Master Occupancy'
      value_template: >-
        {%- if (is_state("sensor.master_fan_burglar", "8") or
                is_state("sensor.master_hsm200_burglar", "8")) -%}
          True
        {%- else -%}
          False
        {%- endif -%}

- platform: template
  sensors:
    master_bath_occupancy:
      friendly_name: 'Master Bath Occupancy'
      value_template: >-
        {%- if is_state("sensor.master_bathtub_light_burglar", "8") -%}
          True
        {%- else -%}
          False
        {%- endif -%}

- platform: template
  sensors:
    entry_room_occupancy:
      friendly_name: 'Entry Room Occupancy'
      value_template: >-
        {%- if is_state("sensor.front_porch_lights_burglar", "8") -%}
          True
        {%- else -%}
          False
        {%- endif -%}

- platform: template
  sensors:
    entry_room_occupancy:
      friendly_name: 'Entry Room Occupancy'
      value_template: >-
        {%- if is_state("sensor.front_porch_lights_burglar", "8") -%}
          True
        {%- else -%}
          False
        {%- endif -%}

- platform: template
  sensors:
    master_hall_occupancy:
      friendly_name: 'Master Hall Occupancy'
      value_template: >-
        {%- if is_state("sensor.master_hall_lights_burglar", "8") -%}
          True
        {%- else -%}
          False
        {%- endif -%}

- platform: template
  sensors:
    garage_occupancy:
      friendly_name: 'Garage Occupancy'
      value_template: >-
        {%- if (is_state("sensor.garage_lights_burglar", "8") or
                is_state("cover.ben_garage", "opened") or
                is_state("cover.susan_garage", "opened")) -%}
          True
        {%- else -%}
          False
        {%- endif -%}

- platform: template
  sensors:
    craft_room_occupancy:
      friendly_name: 'Craft Room Occupancy'
      value_template: >-
        {%- if is_state("sensor.craft_room_fan_and_lights_burglar", "8") -%}
          True
        {%- else -%}
          False
        {%- endif -%}

- platform: template
  sensors:
    stairs_occupancy:
      friendly_name: 'Stairs Occupancy'
      value_template: >-
        {%- if is_state("sensor.stairs_light_burglar", "8") -%}
          True
        {%- else -%}
          False
        {%- endif -%}

- platform: template
  sensors:
    gallery_occupancy:
      friendly_name: 'Gallery Occupancy'
      value_template: >-
        {%- if is_state("sensor.gallery_hall_lights_burglar", "8") -%}
          True
        {%- else -%}
          False
        {%- endif -%}

- platform: template
  sensors:
    family_room_occupancy:
      friendly_name: 'Family Room Occupancy'
      value_template: >-
        {%- if (is_state("sensor.breakfast_lights_burglar", "8") or
                is_state("sensor.family_room_mantle_light_burglar", "8")) -%}
          True
        {%- else -%}
          False
        {%- endif -%}

- platform: template
  sensors:
    game_room_occupancy:
      friendly_name: 'Game Room Occupancy'
      value_template: >-
        {%- if is_state("sensor.game_room_fan_burglar", "8") -%}
          True
        {%- else -%}
          False
        {%- endif -%}

- platform: template
  sensors:
    boys_bathroom_occupancy:
      friendly_name: "Boys Bathroom Occupancy"
      value_template: >-
        {%- if is_state("sensor.boys_bathroom_light_burglar", "8") -%}
          True
        {%- else -%}
          False
        {%- endif -%}

- platform: template
  sensors:
    boys_hall_occupancy:
      friendly_name: 'Boys Hall Occupancy'
      value_template: >-
        {%- if is_state("sensor.boys_hall_light_burglar", "8") -%}
          True
        {%- else -%}
          False
        {%- endif -%}

- platform: template
  sensors:
    office_occupancy:
      friendly_name: 'Office Occupancy'
      value_template: >-
        {%- if is_state("sensor.office_lights_dimmer_burglar", "8") -%}
          True
        {%- else -%}
          False
        {%- endif -%}

- platform: template
  sensors:
    girls_hall_occupancy:
      friendly_name: "Girls Hall Occupancy"
      value_template: >-
        {%- if is_state("sensor.girls_hall_light_burglar", "8") -%}
          True
        {%- else -%}
          False
        {%- endif -%}

#- platform: bayesian
#  prior: 0.5
#  name: 'Ben at Home'
#  probability_threshold: 0.9
#  observations:
#    - entity_id: 'device_tracker.arp_ben_iphone'
#      prob_given_true: 0.9
#      prob_given_false: 0.3
#      platform: 'state'
#      to_state: 'home'
#    - entity_id: 'device_tracker.beacon_ben_home'
#      prob_given_true: 0.9
#      prob_given_false: 0.2
#      platform: 'state'
#      to_state: 'home'
#    - entity_id: 'device_tracker.acf9320b92834db89f3da79cdd092ffe'
#      prob_given_true: 0.8
#      prob_given_false: 0.3
#      platform: 'state'
#      to_state: 'home'
#    - entity_id: 'device_tracker.ben_ha_iphone'
#      prob_given_true: 0.8
#      prob_given_false: 0.3
#      platform: 'state'
#      to_state: 'home'

#- platform: bayesian
#  prior: 0.5
#  name: 'Susan at Home'
#  probability_threshold: 0.9
#  observations:
#    - entity_id: 'device_tracker.arp_susan_iphone'
#      prob_given_true: 0.9
#      prob_given_false: 0.3
#      platform: 'state'
#      to_state: 'home'
#    - entity_id: 'device_tracker.beacon_susan_home'
#      prob_given_true: 0.9
#      prob_given_false: 0.2
#      platform: 'state'
#      to_state: 'home'
#    - entity_id: 'device_tracker.cab02f4d94ab43e09ca603aef8faa57b'
#      prob_given_true: 0.8
#      prob_given_false: 0.3
#      platform: 'state'
#      to_state: 'home'
#    - entity_id: 'device_tracker.susan_ha_iphone'
#      prob_given_true: 0.8
#      prob_given_false: 0.3
#      platform: 'state'
#      to_state: 'home'

#- platform: bayesian
#  prior: 0.5
#  name: 'Heidi at Home'
#  probability_threshold: 0.9
#  observations:
#    - entity_id: 'device_tracker.arp_heidi_iphone'
#      prob_given_true: 0.9
#      prob_given_false: 0.3
#      platform: 'state'
#      to_state: 'home'
#    - entity_id: 'device_tracker.beacon_heidi_home'
#      prob_given_true: 0.9
#      prob_given_false: 0.2
#      platform: 'state'
#      to_state: 'home'
#    - entity_id: 'device_tracker.0f37f6226f6e4e39a254ce222bdf30ba'
#      prob_given_true: 0.8
#      prob_given_false: 0.3
#      platform: 'state'
#      to_state: 'home'
