- platform: ring
  monitored_conditions:
    - ding
    - motion

- platform: hikvision
  host: !secret alibi_dvr_ip
  username: !secret alibi_rtsp_username
  password: !secret alibi_rtsp_password

#Occupancy Template Sensors
- platform: template
  sensors:
    guest_occupancy:
      friendly_name: 'Guest Occupancy'
      value_template: >-
        {%- if is_state("sensor.guest_fan_and_lights_burglar", "8") -%}
          True
        {%- else -%}
          False
        {%- endif -%}
    guest_bathroom_occupancy:
      friendly_name: 'Guest Bathroom Occupancy'
      value_template: >-
        {%- if is_state("sensor.guest_bath_lights_burglar", "8") -%}
          True
        {%- else -%}
          False
        {%- endif -%}
    dining_room_occupancy:
      friendly_name: 'Dining Occupancy'
      value_template: >-
        {%- if is_state("sensor.dining_room_lights_burglar", "8") -%}
          True
        {%- else -%}
          False
        {%- endif -%}
    laundry_room_occupancy:
      friendly_name: 'Laundry Room Occupancy'
      value_template: >-
        {%- if is_state("sensor.laundry_lights_burglar", "8") -%}
          True
        {%- else -%}
          False
        {%- endif -%}
    master_occupancy:
      friendly_name: 'Master Occupancy'
      value_template: >-
        {%- if is_state("sensor.master_fan_burglar", "8") -%}
          True
        {%- else -%}
          False
        {%- endif -%}
    master_bath_occupancy:
      friendly_name: 'Master Bath Occupancy'
      value_template: >-
        {%- if is_state("sensor.master_bathtub_light_burglar", "8") -%}
          True
        {%- else -%}
          False
        {%- endif -%}
    entry_room_occupancy:
      friendly_name: 'Entry Room Occupancy'
      value_template: >-
        {%- if is_state("sensor.front_porch_lights_burglar", "8") -%}
          True
        {%- else -%}
          False
        {%- endif -%}
    master_hall_occupancy:
      friendly_name: 'Master Hall Occupancy'
      value_template: >-
        {%- if is_state("sensor.master_hall_lights_burglar", "8") -%}
          True
        {%- else -%}
          False
        {%- endif -%}
    garage_occupancy:
      friendly_name: 'Garage Occupancy'
      value_template: >-
        {%- if (is_state("sensor.garage_lights_burglar", "8") or
                is_state("binary_sensor.garage_door", "on") or
                not is_state("cover.ben_garage", "closed") or
                not is_state("cover.susan_garage", "closed")) -%}
          True
        {%- else -%}
          False
        {%- endif -%}
    craft_room_occupancy:
      friendly_name: 'Craft Room Occupancy'
      value_template: >-
        {%- if is_state("sensor.craft_lights_burglar", "8") -%}
          True
        {%- else -%}
          False
        {%- endif -%}
    stairs_occupancy:
      friendly_name: 'Stairs Occupancy'
      value_template: >-
        {%- if is_state("sensor.stairs_light_burglar", "8") -%}
          True
        {%- else -%}
          False
        {%- endif -%}
    gallery_occupancy:
      friendly_name: 'Gallery Occupancy'
      value_template: >-
        {%- if is_state("sensor.gallery_lights_burglar", "8") -%}
          True
        {%- else -%}
          False
        {%- endif -%}
    family_room_occupancy:
      friendly_name: 'Family Room Occupancy'
      value_template: >-
        {%- if (is_state("sensor.breakfast_lights_burglar", "8") or
                is_state("sensor.family_mantle_lights_burglar", "8")) -%}
          True
        {%- else -%}
          False
        {%- endif -%}
    game_room_occupancy:
      friendly_name: 'Game Room Occupancy'
      value_template: >-
        {%- if is_state("sensor.game_room_fan_burglar", "8") -%}
          True
        {%- else -%}
          False
        {%- endif -%}
    boys_bathroom_occupancy:
      friendly_name: "Boys Bathroom Occupancy"
      value_template: >-
        {%- if is_state("sensor.boys_bathroom_burglar", "8") -%}
          True
        {%- else -%}
          False
        {%- endif -%}
    boys_hall_occupancy:
      friendly_name: 'Boys Hall Occupancy'
      value_template: >-
        {%- if is_state("sensor.boys_hall_burglar", "8") -%}
          True
        {%- else -%}
          False
        {%- endif -%}
    office_occupancy:
      friendly_name: 'Office Occupancy'
      value_template: >-
        {%- if is_state("sensor.office_fan_switch_burglar", "8") -%}
          True
        {%- else -%}
          False
        {%- endif -%}
    girls_hall_occupancy:
      friendly_name: "Girls Hall Occupancy"
      value_template: >-
        {%- if is_state("sensor.girls_hall_lights_burglar", "8") -%}
          True
        {%- else -%}
          False
        {%- endif -%}
# Camera Motion
# FIXME: If there is an "and" sensor, add another motion sensor that removes
# both of the component sensors.
    breakfast_motion:
      friendly_name: 'Breakfast Motion'
      value_template: >-
        {%- if is_state("sensor.breakfast_lights_burglar", "8") -%}
          True
        {%- else -%}
          False
        {%- endif -%}

    garden_side_and_front_guest_motion:
      friendly_name: 'Garden Side and Front Guest Motion'
      value_template: >-
        {%- if (is_state("binary_sensor.garden_side_yard_motion", "true") and
                is_state("binary_sensor.front_yard_motion", "true")) -%}
          True
        {%- else -%}
          False
        {%- endif -%}
    garden_side_only_motion:
      friendly_name: 'Garden Side Only Motion'
      value_template: >-
        {%- if (is_state("binary_sensor.garden_side_yard_motion", "true") and
                is_state("binary_sensor.front_yard_motion", "false")) -%}
          True
        {%- else -%}
          False
        {%- endif -%}
    front_guest_only_motion:
      friendly_name: 'Front Guest Only Motion'
      value_template: >-
        {%- if (is_state("binary_sensor.front_yard_motion", "true") and
                (is_state("binary_sensor.garden_side_yard_motion", "false") and
                is_state("binary_sensor.driveway_motion", "false"))) -%}
          True
        {%- else -%}
          False
        {%- endif -%}
    guest_front_and_driveway_motion:
      friendly_name: 'Guest Front and Driveway Motion'
      value_template: >-
        {%- if (is_state("binary_sensor.front_yard_motion", "true") and
                is_state("binary_sensor.driveway_motion", "true")) -%}
          True
        {%- else -%}
          False
        {%- endif -%}
    driveway_only_motion:
      friendly_name: 'Driveway Only Motion'
      value_template: >-
        {%- if (is_state("binary_sensor.driveway_motion", "true") and
                is_state("binary_sensor.front_yard_motion", "false")) -%}
          True
        {%- else -%}
          False
        {%- endif -%}
    pool_and_back_gate_motion:
      friendly_name: 'Driveway Only Motion'
      value_template: >-
        {%- if (is_state("binary_sensor.pool_motion", "true") and
                is_state("binary_sensor.back_gate_motion", "true")) -%}
          True
        {%- else -%}
          False
        {%- endif -%}
# Presence
    ben_at_home:
      friendly_name: "Ben at Home"
      device_class: presence
      value_template: >-
        {%- if is_state("device_tracker.life360_ben", "home") -%}
          True
        {%- else -%}
          False
        {%- endif -%}
    susan_at_home:
      friendly_name: "Susan at Home"
      device_class: presence
      value_template: >-
        {%- if is_state("device_tracker.life360_susan", "home") -%}
          True
        {%- else -%}
          False
        {%- endif -%}
    heidi_at_home:
      friendly_name: "Heidi at Home"
      device_class: presence
      value_template: >-
        {%- if is_state("device_tracker.life360_heidi", "home") -%}
          True
        {%- else -%}
          False
        {%- endif -%}

# Presence Home or Away
#- platform: template
#  sensors:
#    ben_at_home:
#      friendly_name: "Ben at Home"
#      device_class: presence
#      value_template: >-
#        {%- if is_state("input_select.ben_presence_dropdown", "Home") -%}
#          True
#        {%- else -%}
#          False
#        {%- endif -%}
#    susan_at_home:
#      friendly_name: "Susan at Home"
#      device_class: presence
#      value_template: >-
#        {%- if is_state("input_select.susan_presence_dropdown", "Home") -%}
#          True
#        {%- else -%}
#          False
#        {%- endif -%}
#    heidi_at_home:
#      friendly_name: "Heidi at Home"
#      device_class: presence
#      value_template: >-
#        {%- if is_state("input_select.heidi_presence_dropdown", "Home") -%}
#          True
#        {%- else -%}
#          False
#        {%- endif -%}
        
- platform: workday
  country: US
  workdays: [mon, tue, wed, thu, fri]
