- platform: hikvision
  host: !secret alibi_dvr_ip
  username: !secret alibi_rtsp_username
  password: !secret alibi_rtsp_password

###############################################################################
# Time of day and workday sensors
###############################################################################
- platform: workday
  country: US
  workdays: [mon, tue, wed, thu, fri]

- platform: tod
  name: weekend_bedtime
  after: '20:30'
  before: '8:00'

- platform: tod
  name: workday_bedtime
  after: '20:30'
  before: '8:00'

- platform: tod
  name: is_dark
  after: sunset
  after_offset: "-00:30:00"
  before: sunrise

- platform: tod
  name: is_light
  after: sunrise
  before_offset: "-00:30:00"
  before: sunset

- platform: template
  sensors:
    garage_occupancy:
      friendly_name: 'Garage Occupancy'
      value_template: >-
        {{ is_state("binary_sensor.garage_motion", "on") or
           is_state("binary_sensor.garage_door", "on") or
           not is_state("cover.ben_garage", "closed") or
           not is_state("cover.susan_garage", "closed") }}

###############################################################################
# Indoor Region Motion
###############################################################################
    family_mantle_and_breakfast_motion:
      friendly_name: 'Family and Breakfast Motion'
      device_class: motion
      value_template: >-
        {{ is_state("binary_sensor.breakfast_motion", "on") and
           is_state("binary_sensor.family_mantle_motion", "on") }}

    family_mantle_or_breakfast_motion:
      friendly_name: 'Family or Breakfast Motion'
      device_class: motion
      value_template: >-
        {{ is_state("binary_sensor.breakfast_motion", "on") or
           is_state("binary_sensor.family_mantle_motion", "on") }}

    dining_and_stairs_motion:
      friendly_name: 'Dining and Stairs Motion'
      device_class: motion
      value_template: >-
        {{ is_state("binary_sensor.kids_study_motion", "on") and
           is_state("binary_sensor.stairs_motion", "on") }}

    dining_stairs_or_master_hall_motion:
      friendly_name: 'Dining, Stairs or Master Hall Motion'
      device_class: motion
      value_template: >-
        {{ is_state("binary_sensor.kids_study_motion", "on") or
           is_state("binary_sensor.master_hall_motion", "on") or
           is_state("binary_sensor.stairs_motion", "on") }}

###############################################################################
# Camera Motion
###############################################################################
    garden_side_and_front_guest_field_motion:
      friendly_name: 'Garden Side and Front Guest Field Motion'
      device_class: motion
      value_template: >-
        {{ is_state("binary_sensor.garden_side_yard_field_motion", "on") and
           is_state("binary_sensor.guest_front_yard_field_motion", "on") }}

    guest_front_and_driveway_field_motion:
      friendly_name: 'Guest Front and Driveway Field Motion'
      device_class: motion
      value_template: >-
        {{ is_state("binary_sensor.guest_front_yard_field_motion", "on") and
           is_state("binary_sensor.driveway_field_motion", "on") }}

    pool_and_back_gate_field_motion:
      friendly_name: 'Pool and Back Gate Field Motion'
      device_class: motion
      value_template: >-
        {{ is_state("binary_sensor.pool_field_motion", "on") and
           is_state("binary_sensor.back_gate_yard_field_motion", "on") }}

    deck_and_pool_field_motion:
      friendly_name: 'Deck and Pool Field Motion'
      device_class: motion
      value_template: >-
        {{ is_state("binary_sensor.pool_field_motion", "on") and
           is_state("binary_sensor.deck_field_motion", "on") }}

    front_porch_or_front_door_activity:
      friendly_name: 'Front Porch and Door Activity'
      device_class: motion
      value_template: >-
        {{ is_state("binary_sensor.front_porch_field_motion", "on") or
           is_state("binary_sensor.front_door_motion", "on") or
           is_state("binary_sensor.front_door", "on") }}


###############################################################################
# Life360
###############################################################################
# Presence
    ben_at_home:
      friendly_name: "Ben at Home"
      device_class: presence
      value_template: >-
        {{ is_state("device_tracker.life360_ben_menchaca", "home") }}
      delay_off: 
        minutes: 2
    susan_at_home:
      friendly_name: "Susan at Home"
      device_class: presence
      value_template: >-
        {{ is_state("device_tracker.life360_susan", "home") }}
      delay_off: 
        minutes: 2
    heidi_at_home:
      friendly_name: "Heidi at Home"
      device_class: presence
      value_template: >-
        {{ is_state("device_tracker.life360_heidi", "home") }}
      delay_off: 
        minutes: 2

###############################################################################
# Garage Door Open
###############################################################################
    ben_garage:
      friendly_name: "Ben Garage"
      device_class: garage_door
      value_template: >-
        {{ not is_state("sensor.ben_garage_status", "Closed") }}  

    susan_garage:
      friendly_name: "Susan Garage"
      device_class: garage_door
      value_template: >-
        {{ not is_state("sensor.susan_garage_status", "Closed") }}  

###############################################################################
# Combined Weekend and Workday and Bedtime
###############################################################################
    bedtime:
      friendly_name: "Bedtime"
      value_template: >-
        {{ (is_state("binary_sensor.workday_sensor", "on") and
            is_state("binary_sensor.workday_bedtime", "on")) or
           (is_state("binary_sensor.workday_sensor", "off") and
            is_state("binary_sensor.weekend_bedtime", "on")) }}

    not_bedtime:
      friendly_name: "Not Bedtime"
      value_template: >-
        {{ (is_state("binary_sensor.workday_sensor", "on") and
            is_state("binary_sensor.workday_bedtime", "off")) or
           (is_state("binary_sensor.workday_sensor", "off") and
            is_state("binary_sensor.weekend_bedtime", "off")) }}
