alexa:
  filter:
    include_entities:
      - light.family_room_lights_59
      - light.craft_floor_lamp_66
      - light.game_room_fan_lights_43
      - light.master_bath_vanity_40
      - light.master_fan_lights_37
      - light.office_lights_dimmer_level
    include_domains:
      - scene
      - switch
      - cover
    exclude_entities:
      - switch.breakfast_lights_switch_2
      - switch.dining_room_lights_switch_2
      - switch.front_porch_lights_switch_2
      - switch.gallery_hall_lights_switch_2
      - switch.game_room_fan_switch_2
      - switch.guest_fan_and_lights_switch_2
      - switch.guest_fan_and_lights_switch_3
      - switch.laundry_room_lights_switch_2
      - switch.master_hall_lights_switch_2
      - switch.stairs_light_switch_2
    #exclude_domains:
  entity_config:
    light.family_room_lights_59:
      name: Family Room Lights
    #  description: The light in the kitchen
    light.craft_floor_lamp_66:
      name: Craft Room Large Lamp
    light.game_room_fan_lights_43:
      name: Game Room Lights
    light.master_bath_vanity_40:
      name: Master Bath Lights
    light.master_fan_lights_37:
      name: Master Fan Lights
    light.office_lights_dimmer_level:
      name: Office Lights
    switch.back_porch_light_62:
      name: Back Porch Lights
    switch.breakfast_lights_switch:
      name: Breakfast Lights
    switch.craft_room_fan_39:
      name: Craft Room Fan
    switch.craft_sewing_lamp_67:
      name: Craft Room Sewing Lamp
    switch.entry_lights_46:
      name: Entry Light
    switch.family_room_fan_55:
      name: Family Room Fan
    switch.mantle_flood_light_58:
      name: Family Room Mantle
    switch.front_porch_lights_switch:
      name: Front Porch Lights
    switch.gallery_hall_lights_switch:
      name: Gallery Hall Lights
    switch.game_room_fan_switch:
      name: Game Room Fan

    #switch.stairs:
    #  display_categories: LIGHT
