alexa:
  filter:
    include_entities:
      - light.game_room
      - light.master_vanity_dimmer
      - switch.master_fan_lights
      - switch.office_fan_lights
    include_domains:
      - scene
      - switch
      - cover
      - script
    exclude_entities:
      - switch.breakfast_lights_2
      - switch.dining_room_lights_2
      - switch.front_porch_lights_2
      - switch.gallery_lights_2
      - switch.game_room_fan_2
      - switch.guest_fan_and_lights_2
      - switch.guest_fan_and_lights_3
      - switch.laundry_lights_2
      - switch.master_hall_lights_2
      - switch.stairs_lights_2
    #exclude_domains:
  entity_config:
    switch.family_fan_lights:
      name: Family Room Lights
    light.game_room:
      name: Game Room Lights
    light.master_vanity_dimmer:
      name: Master Bath Lights
    switch.master_fan_lights:
      name: Master Fan Lights
    switch.office_fan_lights:
      name: Office Fan Lights
    switch.back_porch_lights:
      name: Back Porch Lights
    switch.breakfast_lights:
      name: Breakfast Lights
    switch.craft_fan_and_lights:
      name: Craft Room Fan
    switch.craft_sewing_lights:
      name: Craft Room Sewing Lamp
    switch.entry_lights:
      name: Entry Light
    switch.family_fan:
      name: Family Room Fan
    switch.family_mantle_lights:
      name: Family Room Mantle
    switch.front_porch_lights:
      name: Front Porch Lights
    switch.gallery_lights:
      name: Gallery Hall Lights
    switch.game_room_fan:
      name: Game Room Fan
    script.family_room_tv_power_toggle:
      name: Family Room TV Power
    script.family_room_tv_hdmi_1:
      name: Family Room TV HDMI 1
    script.family_room_tv_hdmi_2:
      name: Family Room TV HDMI 2

    #switch.stairs:
    #  display_categories: LIGHT
