alexa:
  filter:
    include_entities:
      - light.family_room_lights_level_2
      - light.craft_room_floor_lamp_level
      - light.game_room_lights_level
      - light.master_bath_vanity_lights_level
      - light.master_fan_lights_level
      - light.office_fan_dimmer
    include_domains:
      - scene
      - switch
      - cover
    exclude_entities:
      - switch.breakfast_lights_switch_2
      - switch.dining_room_lights_switch_2
      - switch.front_porch_light_switch_2
      - switch.gallery_hall_lights_switch_2
      - switch.game_room_fan_switch_2
      - switch.guest_fan_and_lights_switch_2
      - switch.guest_fan_and_lights_switch_3
      - switch.laundry_room_light_switch_2
      - switch.master_hall_lights_switch_2
      - switch.stairs_light_switch_2
    #exclude_domains:
  entity_config:
    light.family_room_lights_level_2:
      name: Family Room Lights
    #  description: The light in the kitchen
    light.craft_room_floor_lamp_level:
      name: Craft Room Large Lamp
    light.game_room_lights_level:
      name: Game Room Lights
    light.master_bath_vanity_lights_level:
      name: Master Bath Lights
    light.master_fan_lights_level:
      name: Master Fan Lights
    light.office_fan_dimmer:
      name: Office Lights
    switch.back_porch_light_switch_2:
      name: Back Porch Lights
    switch.breakfast_lights_switch:
      name: Breakfast Lights
    switch.craft_room_fan_and_lights_switch:
      name: Craft Room Fan
    switch.craft_room_sewing_lamp_switch_2:
      name: Craft Room Sewing Lamp
    switch.entry_hall_lights_switch:
      name: Entry Light
    switch.family_room_fan_switch:
      name: Family Room Fan
    switch.family_room_mantle_light_switch:
      name: Family Room Mantle
    switch.front_porch_light_switch:
      name: Front Porch Lights
    switch.gallery_hall_lights_switch:
      name: Gallery Hall Lights
    switch.game_room_fan_switch:
      name: Game Room Fan

    #switch.stairs:
    #  display_categories: LIGHT
