alexa:
  filter:
    include_entities:
      - light.family_room_dimmer
      - light.game_room
      - light.master_vanity_dimmer
      - light.master_fan_lights_dimmer
      - light.office_fan_dimmer
    include_domains:
      - scene
      - switch
      - cover
    exclude_entities:
      - switch.breakfast_lights_2
      - switch.dining_room_lights_2
      - switch.front_porch_lights_2
      - switch.gallery_lights_2
      - switch.game_room_fan_2
      - switch.guest_fan_and_lights_2
      - switch.guest_fan_and_lights_3
      - switch.laundry_lights_2
      - switch.master_hall_lights_2
      - switch.stairs_lights_2
    #exclude_domains:
  entity_config:
    light.family_room_dimmer:
      name: Family Room Lights
    light.game_room:
      name: Game Room Lights
    light.master_vanity_dimmer:
      name: Master Bath Lights
    light.master_fan_lights_dimmer:
      name: Master Fan Lights
    light.office_fan_dimmer:
      name: Office Lights
    switch.back_porch_lights:
      name: Back Porch Lights
    switch.breakfast_lights:
      name: Breakfast Lights
    switch.craft_fan_and_lights:
      name: Craft Room Fan
    switch.craft_sewing_lights:
      name: Craft Room Sewing Lamp
    switch.entry_lights:
      name: Entry Light
    switch.family_fan:
      name: Family Room Fan
    switch.family_mantle_lights:
      name: Family Room Mantle
    switch.front_porch_lights:
      name: Front Porch Lights
    switch.gallery_lights:
      name: Gallery Hall Lights
    switch.game_room_fan:
      name: Game Room Fan

    #switch.stairs:
    #  display_categories: LIGHT
