# Stuff to hide in the main interface
#customize_glob:
"sensor.*_alarm_level*":
  hidden: true
"sensor.*_alarm_type*":
  hidden: true
"sensor.*_sourcenodeid*":
  hidden: true
"sensor.*_multisensor_luminance":
  hidden: true
"sensor.*_multisensor_ultraviolet":
  hidden: true
