# Stuff to hide in the main interface
#customize_glob:
"switch.zone_1*":
  hidden: true
"sensor.*_alarm_level*":
  hidden: true
"sensor.*_alarm_type*":
  hidden: true
"sensor.*_sourcenodeid*":
  hidden: true
"sensor.*_burglar*":
  hidden: true
"sensor.*_access_control*":
  hidden: true
"sensor.*_power_management*":
  hidden: true
"sensor.*_multisensor_luminance":
  hidden: true
"sensor.*_multisensor_ultraviolet":
  hidden: true
"sensor.netatmo_*door_*_*":
  hidden: true
"sensor.guest_room_heater_plug_*":
  hidden: true
"sensor.*_power_strip_previous*":
  hidden: true
"sensor.*_power_strip_power*":
  hidden: true
"sensor.*_power_strip_energy*":
  hidden: true
