# Stuff to hide in the main interface
#customize_glob:
"sensor.*_alarm_level*":
  hidden: true
"sensor.*_alarm_type*":
  hidden: true
"sensor.*_sourcenodeid*":
  hidden: true
"sensor.*_burglar*":
  hidden: true
"sensor.*_access_control*":
  hidden: true
"sensor.*_power_management*":
  hidden: true
"sensor.*_interval*":
  hidden: true
"sensor.*_awair_score*":
  hidden: true
"sensor.*_voltage":
  hidden: true
"sensor.*_current":
  hidden: true
"sensor.*_exporting":
  hidden: true
"sensor.*_reading*":
  hidden: true
"sensor.*_multisensor_luminance":
  hidden: true
"sensor.*_multisensor_ultraviolet":
  hidden: true
