# Stuff to hide in the main interface
#customize_glob:
"switch.zone_1*":
  hidden: true
"sensor.*_alarm_level*":
  hidden: true
"sensor.*_alarm_type*":
  hidden: true
"sensor.*_sourcenodeid*":
  hidden: true
"sensor.*_burglar*":
  hidden: true
"sensor.*_access_control*":
  hidden: true
"sensor.*_power_management*":
  hidden: true
"sensor.multisensor_*_luminance":
  hidden: true
"sensor.multisensor_*_ultraviolet":
  hidden: true
"sensor.netatmo_*door_*_*":
  hidden: true
