- platform: geofency
  mobile_beacons:
    - minivan
    - avalon

- platform: nmap_tracker
  scan_options: " --privileged -sP "
  hosts:
  - !secret device_ip_susans_iphone 
  - !secret device_ip_bens_iphone
  - !secret device_ip_heidis_iphone
  track_new_devices: yes

#- platform: owntracks
#  waypoints: False
#  track_new_devices: False
  #consider_home: 60

#- platform: nmap_tracker
#  hosts:
#    - !secret device_ip_noahs_ipad
#    - !secret device_ip_noahs_ipod
#    - !secret device_ip_noahs_kindle
#    - !secret device_ip_hannahs_ipad
#    - !secret device_ip_heidis_ipad
#    - !secret device_ip_heidis_kindle
