- platform: geofency
  consider_home: 60

- platform: arping
  consider_home: 60
  count: 2
  hosts:
   arp_susan_iphone: !secret device_ip_susans_iphone 
   arp_ben_iphone: !secret device_ip_bens_iphone
   arp_heidi_iphone: !secret device_ip_heidis_iphone


#- platform: owntracks
#  waypoints: False
#  track_new_devices: False
  #consider_home: 60

# This is specific to iphones only
#- platform: nmap_tracker
#  scan_options: " --privileged -p 62078 "
#  track_new_devices: yes
#  hosts:
#   - !secret device_ip_susans_iphone 
#   - !secret device_ip_bens_iphone
#   - !secret device_ip_heidis_iphone

#- platform: nmap_tracker
#  hosts:
#    - !secret device_ip_noahs_ipad
#    - !secret device_ip_noahs_ipod
#    - !secret device_ip_noahs_kindle
#    - !secret device_ip_hannahs_ipad
#    - !secret device_ip_heidis_ipad
#    - !secret device_ip_heidis_kindle
