#- platform: geofency
#  consider_home: 60

#- platform: proximity_events
#  consider_home: 60

#- platform: unifi
#  host: !secret device_ip_unifi_controller
#  username: !secret unifi_controller_username
#  password: !secret unifi_controller_password
#  verify_ssl: False
#  ssid_filter:
#    - 'MerlinHome'
#    - 'MerlinKids'

- platform: life360
  username: !secret life360_username
  password: !secret life360_password
  prefix: life360
  show_as_state: places, driving, moving
  max_gps_accuracy: 200
  max_update_wait:
    minutes: 30

- platform: tile
  username: !secret tile_username
  password: !secret tile_password

#- platform: arping
#  consider_home: 60
#  count: 2
#  hosts:
#   arp_susan_iphone: !secret device_ip_susans_iphone
#   arp_ben_iphone: !secret device_ip_bens_iphone
#   arp_heidi_iphone: !secret device_ip_heidis_iphone


# This is specific to iphones only
#- platform: nmap_tracker
#  scan_options: " --privileged -p 62078 "
#  track_new_devices: yes
#  hosts:
#   - !secret device_ip_susans_iphone 
#   - !secret device_ip_bens_iphone
#   - !secret device_ip_heidis_iphone

#- platform: nmap_tracker
#  hosts:
#    - !secret device_ip_noahs_ipad
#    - !secret device_ip_noahs_ipod
#    - !secret device_ip_noahs_kindle
#    - !secret device_ip_hannahs_ipad
#    - !secret device_ip_heidis_ipad
#    - !secret device_ip_heidis_kindle
