      name: downstairs
      image: /local/custom_ui/floorplan/downstairs.svg
      stylesheet: /local/custom_ui/floorplan/floorplan.css
      
      # These options are optional
      warnings:                  # enable warnings (to find out why things might ot be working correctly)
      # pan_zoom:                  # enable experimental panning / zooming
      # hide_app_toolbar:          # hide the application toolbar (when used as a custom panel)
      # date_format: DD-MMM-YYYY   # Date format to use in hover-over text
      
      # last_motion_entity: sensor.template_last_motion
      # last_motion_class: last-motion

      groups:

        - name: Door Sensors
          entities:
            - binary_sensor.master_closet_door_sensor
            - binary_sensor.pantry_door_sensor
            - binary_sensor.laundry_room_closet_door_sensor
            - binary_sensor.front_door
            - binary_sensor.back_door
            - binary_sensor.garage_door
          states:
            - state: 'on'
              class: 'door-opened'
            - state: 'off'
              class: 'door-closed'

        - name: Binary Sensors
          entities:
            - binary_sensor.guest_occupancy
          states:
            - state: 'on'
              class: 'occupancy-on'
            - state: 'off'
              class: 'occupancy-off'
          state_transitions:
            - name: On to Off
              from_state: 'on'
              to_state: 'off'
              duration: 5
            - name: Off to On
              from_state: 'off'
              to_state: 'on'
              duration: 1

        - name: Existance Sensors
          entities:
            - sensor.susan_garage_car_present
            - sensor.ben_garage_car_present
          states:
            - state: 'Yes'
              class: 'existant'
            - state: 'No'
              class: 'non-existant'
            - state: 'n/a'
              class: 'unknown-existance'

        - name: Fans
          entities:
            - switch.guest_fan_and_lights_switch
            - switch.family_room_fan_switch
            - switch.craft_room_fan_switch
          states:
            - state: 'on'
              class: 'fan-on'
            - state: 'off'
              class: 'fan-off'
          action:
            domain: homeassistant
            service: toggle

        - name: Light Switches
          entities:
            - light.family_room_fan_lights_level
            - light.master_bath_vanity_lights_dimmer_level
            - light.master_fan_lights_dimmer_level
            - switch.back_porch_light_switch
            - switch.breakfast_lights_switch
            - switch.craft_room_sewing_lamp_switch
            - switch.dining_room_lights_switch
            - switch.entry_christmas_tree_outlet_switch
            - switch.entry_light_switch
            - switch.family_room_mantle_light_switch
            - switch.front_porch_lights_switch
            - switch.garage_lights_switch
            - switch.garage_outdoor_lights_switch
            - switch.guest_hall_lights_switch
            - switch.guest_bathroom_lights_switch
            - switch.kitchen_lights_switch
            - switch.laundry_room_closet_lights_switch
            - switch.laundry_room_lights_switch
            - switch.master_bath_tub_light_switch
            - switch.master_closet_light_switch
            - switch.master_hall_lights_switch
            - switch.master_lavatory_light_switch
            - switch.pantry_lights_switch
            - switch.stairs_light_switch

          states:
            - state: 'on'
              class: 'light-on'
            - state: 'off'
              class: 'light-off'
          action:
            domain: homeassistant
            service: toggle
