# Uncomment this if you are using SSL or running in Docker etc
#ssl_certificate: !secret http_certificate
#ssl_key: !secret http_key
#server_host: 127.0.0.1
#base_url: !secret http_url
#api_password: !secret http_password
ip_ban_enabled: False
#login_attempts_threshold: 3
#server_port: !secret http_port
#trusted_networks:
#  - 192.168.0.0/16
