#ben_life360_home:
#  name: Life360 Ben Home
#  initial: off
#  icon: mdi:home-account

#susan_life360_home:
#  name: Life360 Susan Home
#  initial: off
#  icon: mdi:home-account

#heidi_life360_home:
#  name: Life360 Heidi Home
#  initial: off
#  icon: mdi:home-account

#someone_life360_home:
#  name: Life360 Someone Home
#  initial: off
# icon: mdi:home-account
