house_mode:
  name: House Mode
  options:
    - Morning
    - Day
    - Evening
    - Night
    - Naptime

ben_presence_dropdown:
  name: Ben Presence
  options:
    - Home
    - Just Arrived
    - Just Left
    - Away

susan_presence_dropdown:
  name: Ben Presence
  options:
    - Home
    - Just Arrived
    - Just Left
    - Away

any_presence_dropdown:
  name: Any Presence
  options:
    - Active
    - Nap
    - Sleep
    - Away
