house_time_of_day:
  name: House Time of Day
  options:
    - Morning
    - Day
    - Naptime
    - Afternoon
    - Evening
    - Night

#ben_presence_dropdown:
#  name: Ben Presence
#  options:
#    - Home
#    - Away

#susan_presence_dropdown:
#  name: Susan Presence
#  options:
#    - Home
#    - Away

#heidi_presence_dropdown:
#  name: Heidi Presence
#  options:
#    - Home
#    - Away
