#- platform: template
#  lights:
#    mantle_light:
#      friendly_name: "Family Room Mantle Light"
#      value_template:
#        " {{ is_state('switch.family_mantle_lights', 'on') }} "
#      turn_on:
#        service: switch.turn_on
#        entity_id: switch.family_mantle_lights
#      turn_off:
#        service: switch.turn_off
#        entity_id: switch.family_mantle_lights
#      level_template: >-
#        {%- if is_state('switch.family_mantle_lights', 'off') -%}
#          {{ 0 }}
#        {%- elif states.light.family_room_flood -%}
#          {{ states(light.family_room_flood.attributes.brightness) }}
#          {{ states.light.family_room_flood.attributes.brightness }}
#        {%- else -%}
#          {{ 0 }}
#        {%- endif -%}  
#      set_level:
#        service: light.turn_on
#        entity_id: light.family_room_flood
#        data_template:
#          # Set both the color and brightness of the light
#          brightness: " {{brightness}} "
#          # Hue can emulate colors from 153 through 500 Mireds
#          # This simply uses the brightness as the variable to select a
#          # Mired value, yielding cooler colors as the light gets brighter
#          color_temp: " {{255 - brightness + 246}} "
##
#- platform: template
#  lights:
#    master_hall_lights:
#      friendly_name: "Master Hall Light"
#      value_template:
#        " {{ is_state('switch.master_hall_lights', 'on') }} "
#      turn_on:
#        service: switch.turn_on
#        entity_id: switch.master_hall_lights
#      turn_off:
#        service: switch.turn_off
#        entity_id: switch.master_hall_lights
#      level_template: >-
#        {%- if is_state('switch.master_hall_lights', 'off') -%}
#          {{ 0 }}
#        {%- elif states.light.master_hall -%}
#          {{ states.light.master_hall.attributes.brightness }}
#        {%- else -%}
#          {{ 0 }}
#        {%- endif -%}  
#      set_level:
#        service: light.turn_on
#        entity_id: light.master_hall
#        data_template:
#          # Set both the color and brightness of the light
#          brightness: " {{brightness}} "
#          # Hue can emulate colors from 153 through 500 Mireds
#          # This simply uses the brightness as the variable to select a
#          # Mired value, yielding cooler colors as the light gets brighter
#          color_temp: " {{255 - brightness + 246}} "
          
#- platform: template
#  lights:
#    gallery_combo:
#      friendly_name: "Gallery Combo Lights"
#      value_template: >-
#        {%- if is_state('switch.gallery_lights', 'on') -%}
#          {{ "on" }}
#        {%- else -%}
#          {{ "off" }}
#        {%- endif -%}  
#      level_template: >-
#        {%- if is_state('switch.gallery_lights', 'off') -%}
#          {{ 0 }}
#        {%- elif states.light.gallery_flood_bulb -%}
#          {{ states.light.gallery_flood_bulb.attributes.brightness }}
#        {%- else -%}
#          {{ 0 }}
#        {%- endif -%}  
#      turn_on:
#        service: switch.turn_on
#        entity_id: switch.gallery_lights
#      turn_off:
#        service: switch.turn_off
#        entity_id: switch.gallery_lights
#      set_level:
#        service: light.turn_on
#        entity_id: light.gallery_flood_bulb
#        data_template:
#          brightness: " {{ brightness }} "

# Fan Light Groups
- platform: group
  name: Heidi Fan Lights
  entities:
    - light.heidi_fan_bulb_1
    - light.heidi_fan_bulb_2
    - light.heidi_fan_bulb_color

- platform: group
  name: Noah Fan Lights
  entities:
    - light.noah_fan_bulb_1
    - light.noah_fan_bulb_2
    - light.noah_fan_bulb_color

- platform: group
  name: Hannah Fan Lights
  entities:
    - light.hannah_fan_bulb_1
    - light.hannah_fan_bulb_2
    - light.hannah_fan_bulb_color

- platform: group
  name: Guest Fan Lights
  entities:
    - light.guest_fan_bulb_1
    - light.guest_fan_bulb_2
    - light.guest_fan_bulb_3
    - light.guest_fan_bulb_4

- platform: group
  name: Game Room Fan Lights
  entities:
    - light.game_fan_bulb_1
    - light.game_fan_bulb_2
    - light.game_fan_bulb_3
    - light.game_fan_bulb_4

- platform: group
  name: Master Fan Lights
  entities:
    - light.master_fan_bulb_1
    - light.master_fan_bulb_2
    - light.master_fan_bulb_3
    - light.master_fan_bulb_4

- platform: group
  name: Office Fan Lights
  entities:
    - light.office_fan_bulb_1
    - light.office_fan_bulb_2
    - light.office_fan_bulb_3
    - light.office_fan_bulb_4

- platform: group
  name: Craft Fan Lights
  entities:
    - light.craft_fan_bulb_1
    - light.craft_fan_bulb_2
    - light.craft_fan_bulb_3

# Room Light Groups
- platform: group
  name: Heidi Room Lights
  entities:
    - light.heidi_fan_bulb_1
    - light.heidi_fan_bulb_2
    - light.heidi_fan_bulb_color
    - light.heidi_go
    - light.heidi_bed_lightstrip
    - light.heidi_closet

- platform: group
  name: Hannah Room Lights
  entities:
    - light.hannah_fan_bulb_1
    - light.hannah_fan_bulb_2
    - light.hannah_fan_bulb_color
    - light.hannah_bed_lightstrip
    - light.hannah_lamp

- platform: group
  name: Noah Room Lights
  entities:
    - light.noah_fan_bulb_1
    - light.noah_fan_bulb_2
    - light.noah_fan_bulb_color
    - light.noah_bed_lightstrip
    - light.noah_lamp

- platform: group
  name: Master Hall Lights
  entities:
    - light.master_hall_bulb_1
    - light.master_hall_bulb_2
    - light.master_hall_bulb_3
  
- platform: group
  name: Guest Bath Lights
  entities:
    - light.guest_bath_bulb_1
    - light.guest_bath_bulb_2
    - light.guest_bath_bulb_color

- platform: group
  name: Office Lights
  entities:
    - light.office_go

# Outside
- platform: group
  name: Back Yard Lights
  entities:
    - light.pool_pump_center_calla
    - light.pool_pump_deck_calla
    - light.pool_pump_gate_calla
    - light.deck_pool_stairs_calla
    - light.deck_big_tree_spot
    - light.deck_bar_lightstrip
    - light.deck_bar_lightstrip_2
    - light.deck_breakfast_stairs_lightstrip
    - light.deck_lower_railing_lightstrip
    - light.deck_lower_lightstrip
    - light.back_porch_light

- platform: group
  name: Pool Pump Lights
  entities:
    - light.pool_pump_center_calla
    - light.pool_pump_deck_calla
    - light.pool_pump_gate_calla

- platform: group
  name: Back Deck Lights
  entities:
    - light.deck_bar_lightstrip
    - light.deck_bar_lightstrip_2
    - light.deck_breakfast_stairs_lightstrip
    - light.deck_lower_railing_lightstrip
    - light.deck_lower_lightstrip
    - light.back_porch_light

# Other Groups
- platform: group
  name: Bedtime Dimmed Lights
  entities:
    - light.guest_bath_bulb_1
    - light.guest_bath_bulb_2
    - light.guest_bath_bulb_color
    - light.master_hall_bulb_1
    - light.master_hall_bulb_2
    - light.master_hall_bulb_3
    - light.gallery_flood_bulb
    - light.family_mantle_bulb

##
# Lights that use the Switch platform
##
- platform: switch
  name: Kitchen Pantry Switch
  entity_id: switch.kitchen_pantry_light

- platform: switch
  name: Laundry Closet Switch
  entity_id: switch.laundry_closet_lights

- platform: switch
  name: Master Closet Switch
  entity_id: switch.master_closet_lights

- platform: switch
  name: Front Porch Switch
  entity_id: switch.front_porch_lights
