# Combo Lights and Switches
- platform: template
  lights:
    gallery_combo:
      friendly_name: "Gallery Combo Lights"
      value_template: >-
        {{ (is_state("switch.gallery_lights", "on") and
            is_state("light.gallery_flood_bulb", "on")) }}
      level_template: >-
        {% if is_state("switch.gallery_lights", "on") %}
          {{ state_attr("light.gallery_flood_bulb", "brightness") | int }}
        {% else %}
          0
        {% endif %}
      temperature_template: >-
        {% if is_state("switch.gallery_lights", "on") %}
          {{ state_attr("light.gallery_flood_bulb", "color_temp") | int }}
        {% else %}
          {{ state_attr("light.gallery_flood_bulb", "min_mireds") }}
        {% endif %}
      turn_on:
        service: scene.turn_on
        entity_id: scene.gallery_turn_on
      turn_off:
        service: switch.turn_off
        entity_id: switch.gallery_lights
      set_level:
        service: light.turn_on
        entity_id: light.gallery_flood_bulb
        data_template:
          brightness: " {{ brightness }} "
      set_temperature:
        service: light.turn_on
        entity_id: light.gallery_flood_bulb
        data_template:
          color_temp: " {{ color_temp }} "

- platform: template
  lights:
    guest_bath_combo:
      friendly_name: "Guest Bath Combo Lights"
      value_template: >-
        {{ (is_state("switch.guest_bath_lights", "on") and
            is_state("light.guest_bath_lights", "on")) }}
      level_template: >-
        {% if is_state("switch.guest_bath_lights", "on") %}
          {{ state_attr("light.guest_bath_lights", "brightness") | int }}
        {% else %}
          0
        {% endif %}
      temperature_template: >-
        {% if is_state("switch.guest_bath_lights", "on") %}
          {{ state_attr("light.guest_bath_lights", "color_temp") | int }}
        {% else %}
          {{ state_attr("light.guest_bath_lights", "min_mireds") }}
        {% endif %}
      turn_on:
        service: scene.turn_on
        entity_id: scene.guest_bath_on
      turn_off:
        service: switch.turn_off
        entity_id: switch.guest_bath_lights
      set_level:
        service: light.turn_on
        entity_id: light.guest_bath_lights
        data_template:
          brightness: " {{ brightness }} "
      set_temperature:
        service: light.turn_on
        entity_id: light.guest_bath_lights
        data_template:
          color_temp: " {{ color_temp }} "

- platform: template
  lights:
    master_hall_combo:
      friendly_name: "Master Hall Combo Lights"
      value_template: >-
        {{ (is_state("switch.master_hall_lights", "on") and
            is_state("light.master_hall_lights", "on")) }}
      level_template: >-
        {% if is_state("switch.master_hall_lights", "on") %}
          {{ state_attr("light.master_hall_lights", "brightness") | int }}
        {% else %}
          0
        {% endif %}
      temperature_template: >-
        {% if is_state("switch.master_hall_lights", "on") %}
          {{ state_attr("light.master_hall_lights", "color_temp") | int }}
        {% else %}
          {{ state_attr("light.master_hall_lights", "min_mireds") }}
        {% endif %}
      turn_on:
        service: scene.turn_on
        entity_id: scene.master_hall_on
      turn_off:
        service: switch.turn_off
        entity_id: switch.master_hall_lights
      set_level:
        service: light.turn_on
        entity_id: light.master_hall_lights
        data_template:
          brightness: " {{ brightness }} "
      set_temperature:
        service: light.turn_on
        entity_id: light.master_hall_lights
        data_template:
          color_temp: " {{ color_temp }} "

- platform: template
  lights:
    family_mantle_combo:
      friendly_name: "Family Mantle Combo Lights"
      value_template: >-
        {{ (is_state("switch.family_mantle_lights", "on") and
            is_state("light.family_mantle_bulb", "on")) }}
      level_template: >-
        {% if is_state("switch.family_mantle_lights", "on") %}
          {{ state_attr("light.family_mantle_bulb", "brightness") | int }}
        {% else %}
          0
        {% endif %}
      temperature_template: >-
        {% if is_state("switch.family_mantle_lights", "on") %}
          {{ state_attr("light.family_mantle_bulb", "color_temp") | int }}
        {% else %}
          {{ state_attr("light.family_mantle_bulb", "min_mireds") }}
        {% endif %}
      turn_on:
        service: scene.turn_on
        entity_id: scene.family_mantle_on
      turn_off:
        service: switch.turn_off
        entity_id: switch.family_mantle_lights
      set_level:
        service: light.turn_on
        entity_id: light.family_mantle_bulb
        data_template:
          brightness: " {{ brightness }} "
      set_temperature:
        service: light.turn_on
        entity_id: light.family_mantle_bulb
        data_template:
          color_temp: " {{ color_temp }} "

- platform: template
  lights:
    game_room_combo:
      friendly_name: "Game Room Combo Lights"
      value_template: >-
        {{ (is_state("switch.game_room_lights", "on") and
            is_state("light.game_room_lights", "on")) }}
      level_template: >-
        {% if is_state("switch.game_room_lights", "on") %}
          {{ state_attr("light.game_room_lights", "brightness") | int }}
        {% else %}
          0
        {% endif %}
      turn_on:
        service: scene.turn_on
        entity_id: scene.game_room_on
      turn_off:
        service: switch.turn_off
        entity_id: switch.game_room_lights
      set_level:
        service: light.turn_on
        entity_id: light.game_room_lights
        data_template:
          brightness: " {{ brightness }} "


# Fan Light Groups
- platform: group
  name: Heidi Fan Lights
  entities:
    - light.heidi_fan_bulb_1
    - light.heidi_fan_bulb_2
    - light.heidi_fan_bulb_color

- platform: group
  name: Noah Fan Lights
  entities:
    - light.noah_fan_bulb_1
    - light.noah_fan_bulb_2
    - light.noah_fan_bulb_color

- platform: group
  name: Hannah Fan Lights
  entities:
    - light.hannah_fan_bulb_1
    - light.hannah_fan_bulb_2
    - light.hannah_fan_bulb_color

- platform: group
  name: Guest Fan Lights
  entities:
    - light.guest_fan_bulb_1
    - light.guest_fan_bulb_2
    - light.guest_fan_bulb_3
    - light.guest_fan_bulb_4

- platform: group
  name: Game Room Lights
  entities:
    - light.game_fan_bulb_1
    - light.game_fan_bulb_2
    - light.game_fan_bulb_3
    - light.game_fan_bulb_4

- platform: group
  name: Master Fan Lights
  entities:
    - light.master_fan_bulb_1
    - light.master_fan_bulb_2
    - light.master_fan_bulb_3
    - light.master_fan_bulb_4

- platform: group
  name: Craft Fan Lights
  entities:
    - light.craft_fan_bulb_1
    - light.craft_fan_bulb_2
    - light.craft_fan_bulb_3

# Room Light Groups
- platform: group
  name: Heidi Room Lights
  entities:
    - light.heidi_fan_bulb_1
    - light.heidi_fan_bulb_2
    - light.heidi_fan_bulb_color
    - light.heidi_go
    - light.heidi_bed_lightstrip
    - light.heidi_closet

- platform: group
  name: Hannah Room Lights
  entities:
    - light.hannah_fan_bulb_1
    - light.hannah_fan_bulb_2
    - light.hannah_fan_bulb_color
    - light.hannah_bed_lightstrip
    - light.hannah_lamp

- platform: group
  name: Noah Room Lights
  entities:
    - light.noah_fan_bulb_1
    - light.noah_fan_bulb_2
    - light.noah_fan_bulb_color
    - light.noah_bed_lightstrip
    - light.noah_lamp

- platform: group
  name: Master Hall Lights
  entities:
    - light.master_hall_bulb_1
    - light.master_hall_bulb_2
    - light.master_hall_bulb_3
  
- platform: group
  name: Guest Bath Lights
  entities:
    - light.guest_bath_bulb_1
    - light.guest_bath_bulb_2
    - light.guest_bath_bulb_color

- platform: group
  name: Office Lights
  entities:
    - light.office_go

# Outside
- platform: group
  name: Back Yard Lights
  entities:
    - light.pool_pump_center_calla
    - light.pool_pump_deck_calla
    - light.pool_pump_gate_calla
    - light.deck_pool_stairs_calla
    - light.deck_big_tree_spot
    - light.deck_bar_lightstrip
    - light.deck_bar_lightstrip_2
    - light.deck_breakfast_stairs_lightstrip
    - light.deck_lower_railing_lightstrip
    - light.deck_lower_lightstrip
    - light.back_porch_light

- platform: group
  name: Pool Pump Lights
  entities:
    - light.pool_pump_center_calla
    - light.pool_pump_deck_calla
    - light.pool_pump_gate_calla

- platform: group
  name: Back Deck Lights
  entities:
    - light.deck_bar_lightstrip
    - light.deck_bar_lightstrip_2
    - light.deck_breakfast_stairs_lightstrip
    - light.deck_lower_railing_lightstrip
    - light.deck_lower_lightstrip
    - light.back_porch_light

# Other Groups
- platform: group
  name: Bedtime Dimmed Lights
  entities:
    - light.guest_bath_bulb_1
    - light.guest_bath_bulb_2
    - light.guest_bath_bulb_color
    - light.master_hall_lights_bulb_1
    - light.master_hall_lights_bulb_2
    - light.master_hall_lights_bulb_3
    - light.gallery_flood_bulb
    - light.family_mantle_bulb

##
# Lights that use the Switch platform
##
- platform: switch
  name: Kitchen Pantry Switch
  entity_id: switch.kitchen_pantry_light

- platform: switch
  name: Laundry Closet Switch
  entity_id: switch.laundry_closet_lights

- platform: switch
  name: Master Closet Switch
  entity_id: switch.master_closet_lights

- platform: switch
  name: Front Porch Switch
  entity_id: switch.front_porch_lights
