default: info
#default: debug
logs:
  homeassistant.components.automation: info
  # homeassistant.components.scene: debug
  # homeassistant.components.automation: debug
  # homeassistant.components.script: debug
  # homeassistant.components.light: debug
  # homeassistant.components.switch: debug
  # homeassistant.components.cover: debug
  # homeassistant.components.device_tracker: debug
