- name: guest_unoccupied
  entities:
    light.guest: off

- name: craft_room_switch_off
  entities:
    switch.craft_fan_and_lights: off
    switch.craft_sewing_lights: off
    
- name: craft_room_switch_on
  entities:
    switch.craft_fan_and_lights: on
    switch.craft_sewing_lights: on

- name: family_room_lights_off
  entities:
    switch.breakfast_lights: off
    switch.kitchen_lights: off
    switch.back_porch_light_switch_2: off
    light.family_room_dimmer:
      state: off

- name: entry_hall_off
  entities:
    switch.entry_lights: off
    light.entry_lamp: off

- name: game_room_off
  entities:
    switch.game_room_fan: off
    light.game_room: off
    #    light.game_room:
    #  state: off
  
- name: christmas_lights_daytime
  entities:
    switch.entry_christmas_lights: off

- name: christmas_lights_nighttime
  entities:
    switch.entry_christmas_lights: on

- name: garage_outdoor_lights_daytime
  entities:
    switch.garage_carriage_lights: off

- name: garage_outdoor_lights_nighttime
  entities:
    switch.garage_carriage_lights: on

- name: game_room_on
  entities:
    switch.game_room_fan: on
    light.game_room:
      state: on
    light.game_room: on

- name: deck_lights_evening_on
  entities:
    switch.back_porch_light_switch_2: on
    light.upper_deck_bar_lightstrip: on
    light.upper_deck_bar_lightstrip_2: on
    light.upper_deck_breakfast_stairs_lightstrip: on
    light.upper_deck_tree_spot_light: on
    light.lower_deck_railing_lightstrip: on
    light.lower_deck_stairs_lightstrip: on
    light.lower_deck_stairs_bollard: on
    light.back_porch_light: on
    light.pool_pump_garden_deck: on
    light.pool_pump_garden_center: on
    light.pool_pump_garden_gate: on
    
- name: evening_tv_time
  entities:
    switch.boys_hall_light: off
    switch.girls_hall_lights: off
    light.gallery_flood: off
    light.game_room: off
    switch.back_porch_light_switch_2: off
    switch.master_hall_lights_switch: off
    switch.kitchen_lights: off
    switch.dining_room_lights: off
    switch.stairs_lights: off
    switch.breakfast_lights: off
    switch.entry_lights: off
    switch.guest_batroom_lights_switch: off
    switch.guest_hallway_lights: off
    light.family_room_dimmer: off
    switch.family_mantle_lights: on

- name: house_bed_time
  entities:
    switch.boys_hall_light: off
    switch.girls_hall_lights: off
    light.gallery_flood: off
    switch.stairs_lights: off
    light.game_room: off
    switch.master_hall_lights_switch: off
    switch.kitchen_lights: off
    switch.dining_room_lights: off
    switch.breakfast_lights: off
    switch.entry_lights: off
    switch.entry_christmas_lights: off
    light.family_room_dimmer: off
    switch.family_mantle_lights: off
    switch.back_porch_light_switch_2: off
    switch.front_porch_light_switch: off
    switch.garage_lights: off
    switch.guest_hallway_lights: off
    light.office_fan_dimmer: off
    light.back_porch: off
    cover.ben_garage: closed
    cover.susan_garage: closed

- name: night_switches
  entities:
    switch.noahs_hall_light_switch: off
    switch.girls_hall_lights: off
    # These are on because we will turn the lights off with hue
    switch.gallery_lights: on
    switch.guest_bath_lights: on


- name: everyone_away
  entities:
    switch.garage_lights: off

- name: someone_arriving_home
  entities:
    switch.garage_lights: on

- name: guest_bath_night_time
  entities:
    switch.guest_bath_lights: on
    light.guest_bath_1: off
    light.guest_bath_2: off
    light.guest_bath_color:
      state: on
      brightness: 10
      rgb_color: [20, 0, 0]


