- name: guest_unoccupied
  entities:
    light.guest: off

- name: craft_room_switch_off
  entities:
    switch.craft_fan_and_lights: off
    light.
    
- name: craft_room_switch_on
  entities:
    switch.craft_fan_and_lights: on

- name: family_room_lights_off
  entities:
    switch.breakfast_lights: off
    switch.kitchen_lights: off
    switch.back_porch_lights: off
    switch.family_fan_lights: off

- name: kids_study_off
  entities:
    switch.kids_study_lights: off
    light.hannah_desk_strip: off
    light.heidi_desk_strip: off
    light.noah_desk_strip: off

- name: kids_study_on
  entities:
    switch.kids_study_lights: on
    light.hannah_desk_strip: on
    light.heidi_desk_strip: on
    light.noah_desk_strip: on

- name: entry_hall_off
  entities:
    switch.entry_lights: off
    switch.entry_lamp: off

- name: master_hall_not_night
  entities:
    switch.master_hall_lights: on
    light.master_hall:
      state: on
      color_temp: 429
      brightness: 254

- name: game_room_off
  entities:
    switch.game_room_fan: off
    light.game_room: off
  
- name: christmas_lights_daytime
  entities:
    switch.entry_christmas_lights: off

- name: christmas_lights_nighttime
  entities:
    switch.entry_christmas_lights: on

- name: garage_outdoor_lights_daytime
  entities:
    switch.garage_carriage_lights: off

- name: garage_outdoor_lights_nighttime
  entities:
    switch.garage_carriage_lights: on

- name: game_room_on
  entities:
    switch.game_room_fan: on
    light.game_room: on

- name: gallery_day_time
  entities:
    switch.gallery_lights: on
    light.gallery:
      state: on
      color_temp: 429
      brightness: 254

- name: gallery_night_time
  entities:
    switch.gallery_lights: on
    light.gallery:
      state: on
      color_temp: 500
      brightness: 5

- name: game_room_not_night
  entities:
    switch.game_room_lights: on

- name: game_room_night
  entities:
    switch.game_room_lights: on

- name: guest_bath_night
  entities:
    switch.guest_bath_lights: on
    light.guest_bath_bulb_1: off
    light.guest_bath_bulb_2: off
    light.guest_bath_bulb_color:
      state: on
      color_temp: 500
      brightness: 5

- name: guest_bath_day
  entities:
    switch.guest_bath_lights: on
    light.guest_bath:
      state: on
      color_temp: 429
      brightness: 255

- name: family_night
  entities:
    switch.family_mantle_lights: on
    light.family_mantle_bulb:
      state: on
      color_temp: 500
      brightness: 2

- name: backyard_lights_evening_on
  entities: 
    switch.back_porch_lights: on
    light.back_yard:
      state: on
      color_temp: 429
      brightness: 255

- name: backyard_lights_off
  entities: 
    switch.back_porch_lights: off
    light.back_yard_lights: off
         
- name: evening_tv_time
  entities:
    switch.boys_hall_light: off
    switch.girls_hall_lights: off
    light.gallery_flood: off
    light.game_room: off
    switch.back_porch_lights: off
    switch.master_hall_lights: off
    switch.kitchen_lights: off
    switch.kids_study_lights: off
    switch.stairs_lights: off
    switch.breakfast_lights: off
    switch.entry_lights: off
    switch.guest_bath_lights: off
    switch.guest_hall_lights: off
    switch.family_fan_lights: off
    switch.family_mantle_lights: on

- name: house_bed_time
  entities:
    switch.garage_carriage_lights: on
    switch.garage_lights: off
    switch.front_porch_lights: off
    light.back_yard_lights: off
    cover.ben_garage: closed
    cover.susan_garage: closed

- name: night_switches
  entities:
    switch.noahs_hall_light_switch: off
    switch.girls_hall_lights: off
    # These are on because we will turn the lights off with hue
    switch.guest_bath_lights: on

- name: bedtime_dimmed_lights
  entities:
    light.guest_bath_bulb_1: off
    light.guest_bath_bulb_2: off
    light.guest_bath_bulb_color:
      state: on
      brightness: 5
      kelvin: 2000
    light.gallery_flood_bulb:
      state: on
      brightness: 5
      kelvin: 2000
    light.family_mantle_bulb: 
      state: on
      brightness: 5
      kelvin: 2000

- name: daytime_regular_lights
  entities:
    light.guest_bath_bulb_1:
      state: on
      brightness: 100
      kelvin: 3000
    light.guest_bath_bulb_2:
      state: on
      brightness: 100
      kelvin: 3000
    light.guest_bath_bulb_color:
      state: on
      brightness: 100
      kelvin: 3000
    light.gallery_flood_bulb:
      state: on
      brightness: 100
    light.family_mantle_bulb: 
      state: on
      brightness: 100

- name: everyone_away
  entities:
    switch.garage_lights: off

- name: someone_arriving_home
  entities:
    switch.garage_lights: on

