- name: guest_unoccupied
  entities:
    light.guest: off

- name: craft_room_switch_off
  entities:
    switch.craft_room_fan_switch: off
    switch.craft_room_sewing_lamp_switch: off
    light.craft_room_large_lamp_level:
      state: off
    
- name: craft_room_switch_on
  entities:
    switch.craft_room_fan_switch: on
    switch.craft_room_sewing_lamp_switch: on
    light.craft_room_large_lamp_level:
      state: on
    
- name: game_room_off
  entities:
    switch.game_room_fan_switch: off
    light.game_room: off
    #    light.game_room_fan_lights_dimmer_level:
    #  state: off
  
- name: christmas_lights_daytime
  entities:
    switch.entry_christmas_tree_outlet_switch: off

- name: christmas_lights_nighttime
  entities:
    switch.entry_christmas_tree_outlet_switch: on

- name: garage_outdoor_lights_daytime
  entities:
    switch.garage_outdoor_lights_switch: off

- name: garage_outdoor_lights_nighttime
  entities:
    switch.garage_outdoor_lights_switch: on

- name: game_room_on
  entities:
    switch.game_room_fan_switch: on
    light.game_room_fan_lights_dimmer_level:
      state: on
    light.game_room: on
    
- name: craft_room_switch_off
  entities:
    switch.craft_room_fan_switch: off
    switch.craft_room_sewing_lamp_switch: off
    light.craft_room_large_lamp_level:
      state: off
    
- name: craft_room_switch_on
  entities:
    switch.craft_room_fan_switch: on
    switch.craft_room_sewing_lamp_switch: on
    light.craft_room_large_lamp_level:
      state: on
    
- name: evening_tv_time
  entities:
    switch.noahs_hall_light_switch: off
    switch.girls_hall_light_switch: off
    light.gallery: off
    light.game_room: off
    switch.master_hall_lights_switch: off
    switch.kitchen_lights_switch: off
    switch.dining_room_lights_switch: off
    switch.stairs_light_switch: off
    switch.breakfast_lights_switch: off
    switch.entry_light_switch: off
    switch.guest_bathroom_lights_switch: off
    switch.guest_hall_lights_switch: off
    light.family_room_fan_lights_level:
      state: off
    light.mantle_light:
      state: on

- name: house_bed_time
  entities:
    switch.noahs_hall_light_switch: off
    switch.girls_hall_light_switch: off
    light.gallery: off
    switch.stairs_light_switch: off
    light.game_room: off
    switch.master_hall_lights_switch: off
    switch.kitchen_lights_switch: off
    switch.dining_room_lights_switch: off
    switch.breakfast_lights_switch: off
    switch.entry_light_switch: off
    switch.entry_christmas_tree_outlet_switch: off
    light.family_room_fan_lights_level:
      state: off
    switch.family_room_mantle_light_switch: off
    switch.back_porch_light_switch: off
    switch.front_porch_light_switch: off
    switch.garage_lights_switch: off
    cover.ben_garage: closed
    cover.susan_garage: closed

- name: everyone_away
  entities:
    switch.garage_lights_switch: off

- name: someone_arriving_home
  entities:
    switch.garage_lights_switch: on
