- name: guest_unoccupied
  entities:
    light.guest: off

- name: craft_room_switch_off
  entities:
    switch.craft_room_fan_and_lights_switch: off
    switch.craft_sewing_lamp_67: off
    light.craft_floor_lamp_66:
      state: off
    
- name: craft_room_switch_on
  entities:
    switch.craft_room_fan_and_lights_switch: on
    switch.craft_sewing_lamp_67: on
    light.craft_floor_lamp_66:
      state: on
    
- name: game_room_off
  entities:
    switch.game_room_fan_switch: off
    light.game_room: off
    #    light.game_room_fan_lights_43:
    #  state: off
  
- name: christmas_lights_daytime
  entities:
    switch.christmas_tree_54: off

- name: christmas_lights_nighttime
  entities:
    switch.christmas_tree_54: on

- name: garage_outdoor_lights_daytime
  entities:
    switch.garage_outdoor_light_53: off

- name: garage_outdoor_lights_nighttime
  entities:
    switch.garage_outdoor_light_53: on

- name: game_room_on
  entities:
    switch.game_room_fan_switch: on
    light.game_room_fan_lights_43:
      state: on
    light.game_room: on
    
- name: evening_tv_time
  entities:
    switch.noahs_hall_light_switch: off
    switch.girls_hall_light_switch: off
    light.gallery: off
    light.game_room: off
    switch.master_hall_lights_switch: off
    switch.kitchen_light_56: off
    switch.dining_room_lights_switch: off
    switch.stairs_light_switch: off
    switch.breakfast_lights_switch: off
    switch.entry_lights_46: off
    switch.guest_batroom_lights_switch: off
    switch.guest_hall_lights_switch_2: off
    light.family_room_lights_59:
      state: off
    switch.family_room_mantle_light_switch: on

- name: house_bed_time
  entities:
    switch.noahs_hall_light_switch: off
    switch.girls_hall_light_switch: off
    light.gallery: off
    switch.stairs_light_switch: off
    light.game_room: off
    switch.master_hall_lights_switch: off
    switch.kitchen_light_56: off
    switch.dining_room_lights_switch: off
    switch.breakfast_lights_switch: off
    switch.entry_lights_46: off
    switch.christmas_tree_54: off
    light.family_room_lights_59:
      state: off
    switch.family_room_mantle_light_switch: off
    switch.back_porch_light_62: off
    switch.front_porch_light_switch: off
    switch.garage_lights_switch: off
    switch.guest_hall_lights_switch_2: off
    cover.ben_garage: closed
    cover.susan_garage: closed

- name: night_switches
  entities:
    switch.noahs_hall_light_switch: off
    switch.girls_hall_light_switch: off
    # These are on because we will turn the lights off with hue
    switch.gallery_hall_light_switch: on
    switch.guest_bathroom_lights_switch: on


- name: everyone_away
  entities:
    switch.garage_lights_switch: off

- name: someone_arriving_home
  entities:
    switch.garage_lights_switch: on
