#- platform: ring
#  monitored_conditions:
#    - battery
#    - last_activity
#    - last_ding
#    - last_motion
#    - volume
#    - wifi_signal_category

- platform: wunderground
  api_key: !secret wunderground_api_key
  monitored_conditions:
    - temp_f
    - wind_mph
    - precip_today_in
    - alerts
    - temp_high_1d_f
    - temp_low_1d_f
    - precip_1d
    - precip_1d_in
    - wind_1d_mph
    - weather
    - weather_1d
    - weather_1n
    - weather_2d
    - weather_2n
    - weather_3d
    - weather_3n

- platform: netatmo
  modules:
    Indoor:
      - temperature
      - humidity
      - noise
    Outdoor:
      - temperature
      - humidity
      - battery_vp

        #- platform: arlo
        #  monitored_conditions:
        #    - captured_today
        #    - last_capture
        #    - battery_level
  

- platform: systemmonitor
  resources:
    - type: processor_use
    - type: memory_free
    #- type: disk_free
    #  arg: /

#- platform: usps
#  username: !secret usps_username
#  password: !secret usps_password

#- platform: ups
#  username: !secret ups_username
#  password: !secret ups_password

#- platform: fedex
#  username: !secret fedex_username
#  password: !secret fedex_password

#- platform: template
#  sensors:
#    ben_presence:
#      value_template: >-
#        {%- if ((states.input_select.ben_presence_dropdown.state == "Away") or
#                (states.input_select.ben_presence_dropdown.state == "Extended Away")) %}
#          '{{ states.device_tracker.ben_iphone.state }}'
#        {% else %}
#          '{{ states.input_select.ben_presence_dropdown.state }}'
#        {% endif %}
#      friendly_name: Ben Presence
#    susan_presence:
#      value_template: >-
#        {%- if ((states.input_select.susan_presence_dropdown.state == "Away") or
#                (states.input_select.susan_presence_dropdown.state == "Extended Away")) %}
#          '{{ states.device_tracker.susan_iphone.state }}'
#        {% else %}
#          '{{ states.input_select.susan_presence_dropdown.state }}'
#        {% endif %}
#      friendly_name: Susan Presence
#    any_presence:
#      value_template: '{{ states.input_select.any_presence_dropdown.state }}'
#      friendly_name: Family Presence

- platform: template
  sensors:
    susan_garage_status:
      friendly_name: 'Susan Door Status'
      value_template: >-
        {%- if states.cover.susan_garage %}
          {% if states.cover.susan_garage.attributes["door_state"] == "open" %}
            Open
          {% elif states.cover.susan_garage.attributes["door_state"] == "closed" %}
            Closed
          {% elif states.cover.susan_garage.attributes["door_state"] == "opening" %}
            Opening
          {% elif states.cover.susan_garage.attributes["door_state"] == "closing" %}
            Closing
          {% else %}
            Unknown
          {% endif %}
        {% else %}
          n/a
        {% endif %}

    ben_garage_status:
      friendly_name: 'Ben Door Status'
      value_template: >-
        {%- if states.cover.ben_garage %}
          {% if states.cover.ben_garage.attributes["door_state"] == "open" %}
            Open
          {% elif states.cover.ben_garage.attributes["door_state"] == "closed" %}
            Closed
          {% elif states.cover.ben_garage.attributes["door_state"] == "opening" %}
            Opening
          {% elif states.cover.ben_garage.attributes["door_state"] == "closing" %}
            Closing
          {% else %}
            Unknown
          {% endif %}
        {% else %}
          n/a
        {% endif %}

- platform: template
  sensors:
    susan_garage_car_present:
      friendly_name: 'Minivan in Garage'
      value_template: >-
        {%- if states.cover.susan_garage %}
          {% if states.cover.susan_garage.attributes["door_state"] == "open" %}
            n/a
          {% elif ((states.cover.susan_garage.attributes["distance_sensor"] > 75) and (states.cover.susan_garage.attributes["distance_sensor"] < 125)) %}
            Yes
          {% else %}
            No
          {% endif %}
        {% else %}
          n/a
        {% endif %}
    ben_garage_car_present:
      friendly_name: 'Avalon in Garage'
      value_template: >-
        {%- if states.cover.ben_garage %}
          {% if states.cover.ben_garage.attributes["door_state"] == "open" %}
            n/a
          {% elif ((states.cover.ben_garage.attributes["distance_sensor"] > 70) and (states.cover.ben_garage.attributes["distance_sensor"] < 160)) %}
            Yes
          {% else %}
            No
          {% endif %}
        {% else %}
          n/a
        {% endif %}

