- platform: ring
  monitored_conditions:
    - battery
    - last_activity
    - last_ding
    - last_motion
    - volume
    - wifi_signal_category

#- platform: wunderground
#  api_key: !secret wunderground_api_key
#  monitored_conditions:
#    - temp_f
#    - wind_mph
#    - precip_today_in
#    - alerts
#    - temp_high_1d_f
#    - temp_low_1d_f
#    - precip_1d
#    - precip_1d_in
#    - wind_1d_mph
#    - weather
#    - weather_1d
#    - weather_1n
#    - weather_2d
#    - weather_2n
#    - weather_3d
#    - weather_3n

- platform: netatmo
  modules:
    Indoor:
      - temperature
      - humidity
      - noise
    Outdoor:
      - temperature
      - humidity
      - battery_vp

        #- platform: arlo
        #  monitored_conditions:
        #    - captured_today
        #    - last_capture
        #    - battery_level
  

- platform: systemmonitor
  resources:
    - type: processor_use
    - type: memory_free
    #- type: disk_free
    #  arg: /

#- platform: usps
#  username: !secret usps_username
#  password: !secret usps_password

#- platform: ups
#  username: !secret ups_username
#  password: !secret ups_password

#- platform: fedex
#  username: !secret fedex_username
#  password: !secret fedex_password

#- platform: template
#  sensors:
#    ben_presence:
#      value_template: >-
#        {%- if ((states.input_select.ben_presence_dropdown.state == "Away") or
#                (states.input_select.ben_presence_dropdown.state == "Extended Away")) %}
#          '{{ states.device_tracker.ben_iphone.state }}'
#        {% else %}
#          '{{ states.input_select.ben_presence_dropdown.state }}'
#        {% endif %}
#      friendly_name: Ben Presence
#    susan_presence:
#      value_template: >-
#        {%- if ((states.input_select.susan_presence_dropdown.state == "Away") or
#                (states.input_select.susan_presence_dropdown.state == "Extended Away")) %}
#          '{{ states.device_tracker.susan_iphone.state }}'
#        {% else %}
#          '{{ states.input_select.susan_presence_dropdown.state }}'
#        {% endif %}
#      friendly_name: Susan Presence
#    any_presence:
#      value_template: '{{ states.input_select.any_presence_dropdown.state }}'
#      friendly_name: Family Presence

# All false, not home at all
#- platform: template
#  sensors:
#    ben_home_location:
#      friendly_name: "Ben Home Location"
#      value_template: >-
#        {%- if (is_state("device_tracker.beacon_ben_back_door", "not_home") and
#                is_state("device_tracker.beacon_ben_boys_hall", "not_home") and
#                is_state("device_tracker.beacon_ben_girls_hall", "not_home") and
#                is_state("device_tracker.beacon_ben_front_entry", "not_home") and
#                is_state("device_tracker.beacon_ben_garage", "not_home") and
#                is_state("device_tracker.beacon_ben_master", "not_home")) -%}
#          Not Home
#        {%- elif (is_state("device_tracker.beacon_ben_boys_hall", "ben_boys_hall") and
#                  is_state("device_tracker.beacon_ben_front_entry", "not_home") and
#                  is_state("device_tracker.beacon_ben_front_entry", "not_home")) -%}
#          Office
#        {%- else -%}
#          Other
#        {%- endif -%}

- platform: template
  sensors:
    susan_garage_status:
      friendly_name: 'Susan Door Status'
      value_template: >-
        {%- if states.cover.susan_garage %}
          {% if states.cover.susan_garage.attributes["door_state"] == "open" %}
            Open
          {% elif states.cover.susan_garage.attributes["door_state"] == "closed" %}
            Closed
          {% elif states.cover.susan_garage.attributes["door_state"] == "opening" %}
            Opening
          {% elif states.cover.susan_garage.attributes["door_state"] == "closing" %}
            Closing
          {% else %}
            Unknown
          {% endif %}
        {% else %}
          n/a
        {% endif %}

    ben_garage_status:
      friendly_name: 'Ben Door Status'
      value_template: >-
        {%- if states.cover.ben_garage %}
          {% if states.cover.ben_garage.attributes["door_state"] == "open" %}
            Open
          {% elif states.cover.ben_garage.attributes["door_state"] == "closed" %}
            Closed
          {% elif states.cover.ben_garage.attributes["door_state"] == "opening" %}
            Opening
          {% elif states.cover.ben_garage.attributes["door_state"] == "closing" %}
            Closing
          {% else %}
            Unknown
          {% endif %}
        {% else %}
          n/a
        {% endif %}

- platform: template
  sensors:
    susan_garage_car_present:
      friendly_name: 'Minivan in Garage'
      value_template: >-
        {%- if states.cover.susan_garage %}
          {% if states.cover.susan_garage.attributes["door_state"] == "open" %}
            n/a
          {% elif ((states.cover.susan_garage.attributes["distance_sensor"] > 75) and (states.cover.susan_garage.attributes["distance_sensor"] < 180)) %}
            Yes
          {% else %}
            No
          {% endif %}
        {% else %}
          n/a
        {% endif %}
    ben_garage_car_present:
      friendly_name: 'Avalon in Garage'
      value_template: >-
        {%- if states.cover.ben_garage %}
          {% if states.cover.ben_garage.attributes["door_state"] == "open" %}
            n/a
          {% elif ((states.cover.ben_garage.attributes["distance_sensor"] > 70) and (states.cover.ben_garage.attributes["distance_sensor"] < 200)) %}
            Yes
          {% else %}
            No
          {% endif %}
        {% else %}
          n/a
        {% endif %}


#- platform: mqtt
#  state_topic: 'bt_location/owner/garage/b0:48:1a:c7:a3:2c'
#  value_template: ' {{ value_json.confidence }} '
#  unit_of_measurement: '%'
#  name: 'Garage BT Ben'
#
#- platform: mqtt
#  state_topic: 'bt_location/owner/back_door/b0:48:1a:c7:a3:2c'
#  value_template: ' {{ value_json.confidence }} '
#  unit_of_measurement: '%'
#  name: 'Back Door BT Ben'
#
#- platform: mqtt
#  state_topic: 'bt_location/owner/front_door/b0:48:1a:c7:a3:2c'
#  value_template: ' {{ value_json.confidence }} '
#  unit_of_measurement: '%'
#  name: 'Front Door BT Ben'
#
#- platform: mqtt
#  state_topic: 'bt_location/owner/master/b0:48:1a:c7:a3:2c'
#  value_template: ' {{ value_json.confidence }} '
#  unit_of_measurement: '%'
#  name: 'Master BT Ben'
#
#- platform: mqtt
#  state_topic: 'bt_location/owner/garage/70:70:0d:ec:b5:04'
#  value_template: ' {{ value_json.confidence }} '
#  unit_of_measurement: '%'
#  name: 'Garage BT Susan'
#
#- platform: mqtt
#  state_topic: 'bt_location/owner/back_door/70:70:0d:ec:b5:04'
#  value_template: ' {{ value_json.confidence }} '
#  unit_of_measurement: '%'
#  name: 'Back Door BT Susan'
#
#- platform: mqtt
#  state_topic: 'bt_location/owner/front_door/70:70:0d:ec:b5:04'
#  value_template: ' {{ value_json.confidence }} '
#  unit_of_measurement: '%'
#  name: 'Front Door BT Susan'
#
#- platform: mqtt
#  state_topic: 'bt_location/owner/master/70:70:0d:ec:b5:04'
#  value_template: ' {{ value_json.confidence }} '
#  unit_of_measurement: '%'
#  name: 'Master BT Susan'
#
#- platform: mqtt
#  state_topic: 'bt_location/owner/garage/74:8d:08:31:ab:9e'
#  value_template: ' {{ value_json.confidence }} '
#  unit_of_measurement: '%'
#  name: 'Garage BT Heidi'
#
#- platform: mqtt
#  state_topic: 'bt_location/owner/back_door/74:8d:08:31:ab:9e'
#  value_template: ' {{ value_json.confidence }} '
#  unit_of_measurement: '%'
#  name: 'Back Door BT Heidi'
#
#- platform: mqtt
#  state_topic: 'bt_location/owner/front_door/74:8d:08:31:ab:9e'
#  value_template: ' {{ value_json.confidence }} '
#  unit_of_measurement: '%'
#  name: 'Front Door BT Heidi'
#
#- platform: mqtt
#  state_topic: 'bt_location/owner/master/74:8d:08:31:ab:9e'
#  value_template: ' {{ value_json.confidence }} '
#  unit_of_measurement: '%'
#  name: 'Master BT Heidi'
#
#- platform: min_max
#  name: "Ben BT Occupancy Confidence"
#  type: max
#  round_digits: 0
#  entity_ids:
#    - sensor.garage_bt_ben
#    - sensor.back_door_bt_ben
#    - sensor.front_door_bt_ben
#    - sensor.master_bt_ben
#
#- platform: min_max
#  name: "Susan BT Occupancy Confidence"
#  type: max
#  round_digits: 0
#  entity_ids:
#    - sensor.garage_bt_susan
#    - sensor.back_door_bt_susan
#    - sensor.front_door_bt_susan
#    - sensor.master_bt_susan
#
#- platform: min_max
#  name: "Heidi BT Occupancy Confidence"
#  type: max
#  round_digits: 0
#  entity_ids:
#    - sensor.garage_bt_heidi
#    - sensor.back_door_bt_heidi
#    - sensor.front_door_bt_heidi
#    - sensor.master_bt_heidi
#

- platform: synologydsm
  host: !secret device_ip_synology
  username: !secret synology_username
  password: !secret synology_password
  monitored_conditions:
    - cpu_total_load
    - memory_real_usage
    - volume_percentage_used
