#- platform: wunderground
#  api_key: !secret wunderground_api_key
#  monitored_conditions:
#    - temp_f
#    - wind_mph
#    - precip_today_in
#    - alerts
#    - temp_high_1d_f
#    - temp_low_1d_f
#    - precip_1d
#    - precip_1d_in
#    - wind_1d_mph
#    - weather
#    - weather_1d
#    - weather_1n
#    - weather_2d
#    - weather_2n
#    - weather_3d
#    - weather_3n

#- platform: systemmonitor
#  resources:
#    - type: processor_use
#    - type: memory_free
#    - type: disk_free
#      arg: /

- platform: template
  sensors:
    office_temperature:
      friendly_name: 'Office Temperature'
      value_template: " {{ states('sensor.office_awair_temperature') | round(1) }} "
    office_humidity:
      friendly_name: 'Office Humidity'
      value_template: " {{ states('sensor.office_awair_humidity') | round(1) }} "
    office_co2:
      friendly_name: 'Office CO2'
      value_template: " {{ states('sensor.office_awair_co2') | round(0) }} "
    master_temperature:
      friendly_name: 'Master Temperature'
      value_template: " {{ states('sensor.master_awair_temperature') | round(1) }} "
    master_humidity:
      friendly_name: 'Master Humidity'
      value_template: " {{ states('sensor.master_awair_humidity') | round(1) }} "
    guest_temperature:
      friendly_name: 'Guest Temperature'
      value_template: " {{ states('sensor.guest_awair_temperature') | round(1) }} "
    guest_humidity:
      friendly_name: 'Guest Humidity'
      value_template: " {{ states('sensor.guest_awair_humidity') | round(1) }} "


- platform: template
  sensors:
    susan_garage_status:
      friendly_name: 'Susan Garage Door Status'
      value_template: >-
        {%- if states.cover.susan_garage %}
          {% if states.cover.susan_garage.attributes["door_state"] == "open" %}
            Open
          {% elif states.cover.susan_garage.attributes["door_state"] == "closed" %}
            Closed
          {% elif states.cover.susan_garage.attributes["door_state"] == "opening" %}
            Opening
          {% elif states.cover.susan_garage.attributes["door_state"] == "closing" %}
            Closing
          {% else %}
            Unknown
          {% endif %}
        {% else %}
          n/a
        {% endif %}

    ben_garage_status:
      friendly_name: 'Ben Garage Door Status'
      value_template: >-
        {%- if states.cover.ben_garage %}
          {% if states.cover.ben_garage.attributes["door_state"] == "open" %}
            Open
          {% elif states.cover.ben_garage.attributes["door_state"] == "closed" %}
            Closed
          {% elif states.cover.ben_garage.attributes["door_state"] == "opening" %}
            Opening
          {% elif states.cover.ben_garage.attributes["door_state"] == "closing" %}
            Closing
          {% else %}
            Unknown
          {% endif %}
        {% else %}
          n/a
        {% endif %}

- platform: template
  sensors:
    susan_garage_car_present:
      friendly_name: 'Minivan in Garage'
      value_template: >-
        {%- if states.cover.susan_garage %}
          {% if states.cover.susan_garage.attributes["door_state"] == "open" %}
            n/a
          {% elif ((states.cover.susan_garage.attributes["distance_sensor"] > 75) and (states.cover.susan_garage.attributes["distance_sensor"] < 180)) %}
            Yes
          {% else %}
            No
          {% endif %}
        {% else %}
          n/a
        {% endif %}
    ben_garage_car_present:
      friendly_name: 'Avalon in Garage'
      value_template: >-
        {%- if states.cover.ben_garage %}
          {% if states.cover.ben_garage.attributes["door_state"] == "open" %}
            n/a
          {% elif ((states.cover.ben_garage.attributes["distance_sensor"] > 70) and (states.cover.ben_garage.attributes["distance_sensor"] < 200)) %}
            Yes
          {% else %}
            No
          {% endif %}
        {% else %}
          n/a
        {% endif %}

#- platform: waze_travel_time
#  name: "Waze Ben to Home"
#  origin: device_tracker.life360_ben_menchaca
#  destination: zone.home
#  region: 'US'

#- platform: waze_travel_time
#  name: "Waze Susan to Home"
#  origin: device_tracker.life360_susan
#  destination: zone.home
#  region: 'US'

#- platform: waze_travel_time
#  name: "Waze Heidi to Home"
#  origin: device_tracker.life360_heidi
#  destination: zone.home
#  region: 'US'

#- platform: sql
#  db_url: !secret db_url
#  scan_interval: 7200
#  queries:
#    - name: hass_db_size
#      query: 'SELECT table_schema "database", Round(Sum(data_length + index_length) / 1024 / 1024, 1) "value" FROM information_schema.tables WHERE table_schema="My_Hass_DB" GROUP BY table_schema'
#      column: 'value'
#      unit_of_measurement: MiB
