      name: upstairs
      image: /local/custom_ui/floorplan/upstairs.svg
      stylesheet: /local/custom_ui/floorplan/floorplan.css
      
      # These options are optional
      warnings:                  # enable warnings (to find out why things might ot be working correctly)
      # pan_zoom:                  # enable experimental panning / zooming
      # hide_app_toolbar:          # hide the application toolbar (when used as a custom panel)
      # date_format: DD-MMM-YYYY   # Date format to use in hover-over text
      
      #last_motion_entity: sensor.template_last_motion
      #last_motion_class: last-motion

      groups:
        - name: Binary Sensors
          entities:
            - binary_sensor.office_occupancy
          states:
            - state: 'on'
              class: 'occupancy-on'
            - state: 'off'
              class: 'occupancy-off'

        - name: Fans
          entities:
            - switch.game_room_fan_switch
            - switch.office_fan_switch
            - switch.heidi_room_fan_and_light_switch
          states:
            - state: 'on'
              class: 'fan-on'
            - state: 'off'
              class: 'fan-off'
          action:
            domain: homeassistant
            service: toggle

        - name: Light Switches
          entities:
            - light.game_room_lights_level
            - light.hue_go_1
            - light.office_fan_dimmer
            - switch.boys_bathroom_light
            - switch.boys_hall_light
            - switch.gallery_lights
            - switch.girls_hall_lights
            - switch.office_lamp
            #- switch.office_fan_switch
            - switch.stairs_light_switch
          states:
            - state: 'on'
              class: 'light-on'
            - state: 'off'
              class: 'light-off'
          action:
            domain: homeassistant
            service: toggle

