blueprint:
  name: Scene Switch
  description: Run a scene when a switch is changed
  domain: automation
  input:
    switch_entity:
      name: Switch to Monitor
      selector:
        entity:
          domain: switch
    on_scene:
      name: Scene when Turned On
      selector:
        entity:
          domain: scene
    off_scene:
      name: Scene when Turned Off
      selector:
        entity:
          domain: scene
mode: single
trigger:
  - platform: state
    entity_id: !input switch_entity
    from: "off"
    to: "on"
  - platform: state
    entity_id: !input switch_entity
    from: "on"
    to: "off"
action:
  - choose:
    - conditions: 
      - condition: state
        entity_id: !input switch_entity
        state: "on"
      sequence: 
        - scene: !input on_scene
    - conditions:
      - condition: state
        entity_id: !input switch_entity
        state: "off"
      sequence:   
        - scene: !input off_scene
